# Generated by Django 5.2.5 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('scholarship', 'Scholarship'), ('grant', 'Grant'), ('job', 'Job'), ('internship', 'Internship'), ('fellowship', 'Fellowship'), ('competition', 'Competition'), ('training', 'Training'), ('startup', 'Startup program'), ('funding', 'Business funding'), ('tender', 'Tenders & Procurement')], max_length=24),
        ),
    ]
