# Generated by Django 5.2.5 on 2026-10-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization'),
        ('opportunities', '0002_alter_opportunity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting review'), ('approved', 'Approved'), ('rejected', 'Changes requested')], default='approved', max_length=16),
        ),
    ]
