# Generated by Django 5.2.5 on 2026-10-06 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_organization_opportunity_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityapplication',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
