# Generated by Django 5.2.5 on 2026-10-06 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunity_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='additional_information',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='application_message',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='shared_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OpportunityMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='opportunities.opportunityapplication')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
