# Generated by Django 5.2.5 on 2026-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_mode',
            field=models.CharField(choices=[('external', 'External application'), ('internal', 'Apply on Getneba')], default='external', max_length=16),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='application_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
