# Generated by Django 5.2.5 on 2026-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0010_opportunity_share_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='requires_local_residency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requires_physical_presence',
            field=models.BooleanField(default=False),
        ),
    ]
