# Generated by Django 5.2.5 on 2026-10-10 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_opportunity_tracker_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('input_type', models.CharField(choices=[('url', 'Link'), ('text', 'Pasted text')], max_length=8)),
                ('submitted_url', models.URLField(blank=True, max_length=1000)),
                ('submitted_text', models.TextField(blank=True, max_length=12000)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Checking'), ('completed', 'Completed'), ('failed', 'Could not complete')], db_index=True, default='pending', max_length=16)),
                ('verdict', models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('supported', 'Supported by evidence'), ('suspicious', 'Suspicious'), ('unable', 'Unable to verify')], max_length=16)),
                ('evidence_confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('opportunity_type', models.CharField(blank=True, max_length=80)),
                ('report_summary', models.TextField(blank=True, max_length=2400)),
                ('recommended_action', models.TextField(blank=True, max_length=1200)),
                ('deterministic_checks', models.JSONField(blank=True, default=list)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'input_hash', 'status'], name='opportuniti_user_id_766c18_idx')],
            },
        ),
    ]
