# Generated by Django 5.2.5 on 2026-10-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0013_opportunitycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_channel',
            field=models.CharField(choices=[('website', 'Website'), ('email', 'Email'), ('phone', 'Phone call')], default='website', max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='application_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
