# Generated by Django 5.2.5 on 2026-10-05 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_opportunity_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('organization_type', models.CharField(choices=[('company', 'Company'), ('university', 'University'), ('ngo', 'NGO / Foundation'), ('government', 'Government'), ('startup', 'Startup'), ('other', 'Other')], default='other', max_length=24)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True, max_length=1200)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting verification'), ('verified', 'Verified')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
