# Generated by Django 5.2.5 on 2026-10-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyreport',
            name='task',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
