# Generated by Django 5.2.5 on 2026-10-06 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_safetyreport_task_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='business_industry',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='user',
            name='business_website',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('cv', 'CV / Resume'), ('business_plan', 'Business plan'), ('portfolio', 'Portfolio'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=24)),
                ('name', models.CharField(max_length=180)),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('content_type', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
