# Generated by Django 5.2.5 on 2026-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relocation_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='relocation_preference',
            field=models.CharField(choices=[('not_set', 'Not specified'), ('no', 'Not open to relocating'), ('open', 'Open to relocating'), ('active', 'Actively looking to relocate')], default='not_set', max_length=16),
        ),
    ]
