# Generated by Django 5.2.5 on 2026-09-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_application_contact_phone'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('complete', 'Complete'), ('cancel', 'Cancel'), ('reschedule', 'Reschedule')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_change_decisions', to=settings.AUTH_USER_MODEL)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tasks.task')),
            ],
            options={
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('task',), name='one_pending_task_change')],
            },
        ),
        migrations.CreateModel(
            name='TaskIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('no_show', 'No-show'), ('dispute', 'Dispute')], max_length=16)),
                ('details', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under review'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('resume', 'Resume work'), ('cancel', 'Cancel task'), ('complete', 'Complete task')], max_length=16)),
                ('resolution', models.TextField(blank=True, max_length=1000)),
                ('staff_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_issue_reviews', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='tasks.task')),
            ],
            options={
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'reviewing'))), fields=('task',), name='one_active_task_issue')],
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('client_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tasks.task')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('task', 'sender', 'client_id'), name='unique_message_retry')],
            },
        ),
    ]
