# Generated by Django 5.2.5 on 2026-10-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_application_status_taskchange_taskissue_and_more'),
        ('tasks', '0007_task_nearby_email_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('client_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='booking_note',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('offered', 'Booking offer sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'offered')), fields=('task',), name='one_booking_offer_per_task'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('task',), name='one_accepted_application_per_task'),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.application'),
        ),
        migrations.AddField(
            model_name='applicationmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='applicationmessage',
            constraint=models.UniqueConstraint(fields=('application', 'sender', 'client_id'), name='unique_application_message_retry'),
        ),
    ]
