# Generated by Django 5.2.5 on 2026-10-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_applicationmessage_application_booking_note_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='one_booking_offer_per_task',
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='one_accepted_application_per_task',
        ),
    ]
