import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bell, BookOpen, Briefcase, CalendarClock, Check, Coins, FileText, GraduationCap, Rocket, Search, Target, Trophy, UsersRound } from "lucide-react";
import { jsonLd, publicPageMetadata, siteDescription, siteUrl } from "@/lib/seo";

export const metadata = publicPageMetadata("GetNeba - find opportunities you might qualify for", siteDescription, "/");

const opportunityTypes = [
  { icon: GraduationCap, label: "Scholarships", copy: "Funding for undergraduate, master's, PhD, and other education programs." },
  { icon: Briefcase, label: "Jobs", copy: "Roles matched to your skills, experience, location, and career goals." },
  { icon: Rocket, label: "Startup Programs", copy: "Accelerators, incubators, pitch competitions, and founder programs." },
  { icon: Coins, label: "Grants & Funding", copy: "Funding for individuals, businesses, nonprofits, and startups." },
  { icon: UsersRound, label: "Fellowships", copy: "Professional, academic, leadership, and international programs." },
  { icon: Trophy, label: "Competitions", copy: "Challenges, prizes, and opportunities to showcase your skills." },
  { icon: BookOpen, label: "Training & Certifications", copy: "Free and paid programs to build skills and credentials." },
  { icon: FileText, label: "Tenders & Procurement", copy: "Contracts, procurement notices, supplier opportunities, and tenders." },
];

const goals = ["Get funding for school", "Find your first job", "Build your career", "Start a business", "Fund your startup", "Study abroad", "Learn a new skill", "Find remote work", "Win a competition", "Find contracts for your business"];

export default function LandingPage() {
  return <main className="radar-landing">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": new URL("/#organization", siteUrl).toString(), name: "GetNeba", url: siteUrl.toString(), logo: new URL("/icons/getneba-512.png", siteUrl).toString(), description: siteDescription }, { "@type": "WebSite", "@id": new URL("/#website", siteUrl).toString(), name: "GetNeba", url: siteUrl.toString(), description: siteDescription, inLanguage: "en-NG", publisher: { "@id": new URL("/#organization", siteUrl).toString() } }] }) }} />
    <section className="radar-hero landing-container">
      <div className="radar-hero-copy"><span className="landing-eyebrow"><span className="availability-dot" /> YOUR NEXT OPPORTUNITY IS OUT THERE</span><h1>Stop searching for opportunities.<br /><em>Let them find you.</em></h1><p>Scholarships, grants, jobs, internships, fellowships, training programs, startup funding, tenders, competitions, and more, matched to your profile, goals, and eligibility.</p><div className="landing-hero-actions"><Link href="/register" className="button button-dark">Find my opportunities <ArrowRight size={18} /></Link></div><div className="hero-footnote"><Check size={17} /><span>Free to get started. No endless searching required.</span></div></div>
      <div className="radar-hero-visual"><div className="radar-glow" /><div className="radar-scan" /><div className="radar-card radar-card-main"><div className="radar-card-head"><span className="radar-icon"><Target size={18} /></span><span><small>YOUR OPPORTUNITY RADAR</small><strong>Matches worth your time</strong></span><Bell size={17} /></div><div className="match-item"><span className="match-logo match-purple">92</span><div><strong>Fully Funded Scholarship</strong><small>92% match · Deadline in 18 days</small></div></div><div className="match-item"><span className="match-logo match-orange">87</span><div><strong>Youth Enterprise Grant</strong><small>87% match · Nigeria</small></div></div><div className="match-item"><span className="match-logo match-blue">81</span><div><strong>Developer Internship</strong><small>81% match · Remote</small></div></div><Link className="radar-see-all" href="/register">Find my opportunities <ArrowRight size={15} /></Link></div><div className="radar-pill radar-pill-top"><span className="pill-dot" /> 5 new matches</div><div className="radar-pill radar-pill-bottom"><CalendarClock size={16} /> 2 deadlines approaching</div></div>
    </section>
    <div className="radar-proof"><div className="landing-container"><span><Search size={17} /> Less searching</span><span><Target size={17} /> Better-fit opportunities</span><span><CalendarClock size={17} /> No missed deadlines</span></div></div>
    <section className="radar-section landing-container" id="why"><div className="radar-section-heading"><div><span className="landing-eyebrow">THE PROBLEM</span><h2>Your next opportunity could already be out there.</h2></div><p>Opportunities are published across universities, companies, organizations, and government agencies. The problem is finding the right ones before the deadline.</p></div><div className="radar-problem-copy"><p>GetNeba brings relevant opportunities into one place and helps you understand which ones are actually worth your time.</p></div></section>
    <section className="radar-how" id="how-it-works"><div className="landing-container"><div className="radar-how-intro"><span className="landing-eyebrow">HOW GETNEBA WORKS</span><h2>From searching to <em>taking action.</em></h2><p>Build context once, then use it to make every opportunity easier to understand.</p><Link className="section-link" href="/register">Find my opportunities <ArrowRight size={17} /></Link></div><div className="radar-steps"><article><span className="radar-step-number">01</span><div><h3>Tell us about yourself.</h3><p>Add your education, skills, experience, interests, and goals.</p></div></article><article><span className="radar-step-number">02</span><div><h3>Get matched.</h3><p>Getneba finds opportunities that fit your profile and what you are trying to achieve.</p></div></article><article><span className="radar-step-number">03</span><div><h3>Know why you match.</h3><p>See eligibility, potential gaps, requirements, funding, and deadlines before you apply.</p></div></article><article><span className="radar-step-number">04</span><div><h3>Take action.</h3><p>Save opportunities, track applications, and get reminded before deadlines.</p></div></article></div></div></section>
    <section className="radar-section landing-container" id="opportunities"><div className="radar-section-heading"><div><span className="landing-eyebrow">ONE PLACE FOR OPPORTUNITIES THAT MATTER</span><h2>Find what fits<br /><em>where you are going.</em></h2></div><p>Getneba is built for students, graduates, professionals, founders, and businesses looking for their next opening.</p></div><div className="opportunity-grid">{opportunityTypes.map(({ icon: Icon, label, copy }) => <Link href="/opportunities" className="opportunity-card" key={label}><span className="opportunity-icon"><Icon size={24} /></span><span className="card-arrow"><ArrowUpRight size={18} /></span><h3>{label}</h3><p>{copy}</p></Link>)}</div><Link className="section-link landing-section-cta" href="/opportunities">Explore all opportunities <ArrowRight size={17} /></Link></section>
    <section className="radar-match landing-container"><div className="match-orbit" aria-hidden="true"><div className="orbit-line orbit-line-one" /><div className="orbit-line orbit-line-two" /><span className="orbit-node node-one"><GraduationCap size={17} /></span><span className="orbit-node node-two"><UsersRound size={17} /></span><span className="orbit-node node-three"><Briefcase size={17} /></span><div className="orbit-core"><Target size={38} /><small>YOUR<br />MATCH</small></div></div><div className="radar-match-copy"><span className="landing-eyebrow">KNOW WHY YOU QUALIFY</span><h2>Do not just find opportunities. Know why they fit.</h2><p>Most opportunity websites tell you what exists. Getneba helps answer: is this actually for me?</p><div className="match-list"><span><Check size={16} /> Your match score</span><span><Check size={16} /> Why you match and what is missing</span><span><Check size={16} /> Requirements, benefits, and deadlines</span><span><Check size={16} /> Clear application steps</span></div><Link className="button button-dark" href="/register">Build my profile <ArrowUpRight size={17} /></Link></div></section>
    <section className="radar-section landing-container"><div className="radar-section-heading"><div><span className="landing-eyebrow">BUILT AROUND YOUR GOALS</span><h2>Where are you<br /><em>trying to go?</em></h2></div><p>Whether you want to learn, earn, build, fund, or grow, Getneba helps you discover opportunities aligned with the next step.</p></div><div className="goal-grid">{goals.map((goal) => <span key={goal}>{goal}</span>)}</div></section>
    <section className="radar-inbox landing-container"><div><span className="landing-eyebrow">YOUR OPPORTUNITY INBOX</span><h2>Let useful opportunities<br /><em>come to you.</em></h2><p>Instead of checking dozens of websites every week, let Getneba bring new matches and important deadlines into one place.</p><Link className="section-link" href="/register">See my matches <ArrowRight size={17} /></Link></div><div className="inbox-card"><div><Bell size={17} /><strong>5 new opportunities match your profile</strong></div><span>2 scholarships · 1 internship · 1 grant · 1 fellowship</span><Link href="/register">See my matches <ArrowRight size={15} /></Link></div></section>
    <section className="radar-cta landing-container"><div><span className="landing-eyebrow">START WITH CONTEXT</span><h2>Stop searching.<br /><em>Start discovering.</em></h2><p>Build your opportunity profile once. Let Getneba keep watch.</p></div><Link className="button button-dark" href="/register">Find my opportunities - It&apos;s free <ArrowRight size={18} /></Link></section>
  </main>;
}