import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bell, Bookmark, CalendarClock, Check, Compass, GraduationCap, Search, Sparkles, Target, TrendingUp, UsersRound } from "lucide-react";
import { jsonLd, publicPageMetadata, siteDescription, siteUrl } from "@/lib/seo";

export const metadata = publicPageMetadata("GetNeba — your personal opportunity radar", siteDescription, "/");

const opportunityTypes = [
  { icon: GraduationCap, label: "Scholarships", copy: "Study support that fits your path." },
  { icon: TrendingUp, label: "Jobs & internships", copy: "Work that moves you forward." },
  { icon: Sparkles, label: "Fellowships & programs", copy: "Rooms to learn, lead, and grow." },
  { icon: Target, label: "Grants & competitions", copy: "Funding for your next bold idea." },
];

export default function LandingPage() {
  return <main className="radar-landing">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": new URL("/#organization", siteUrl).toString(), name: "GetNeba", url: siteUrl.toString(), logo: new URL("/icons/getneba-512.png", siteUrl).toString(), description: siteDescription }, { "@type": "WebSite", "@id": new URL("/#website", siteUrl).toString(), name: "GetNeba", url: siteUrl.toString(), description: siteDescription, inLanguage: "en-NG", publisher: { "@id": new URL("/#organization", siteUrl).toString() } }] }) }} />
    <section className="radar-hero landing-container">
      <div className="radar-hero-copy"><span className="landing-eyebrow"><span className="availability-dot" /> YOUR NEXT OPPORTUNITY IS OUT THERE</span><h1>Find the doors<br /><em>meant for you.</em></h1><p>GetNeba brings scholarships, jobs, grants, fellowships, and other opportunities into one personalized radar—so you can spend less time searching and more time moving forward.</p><div className="landing-hero-actions"><Link href="/register" className="button button-dark">Build my opportunity radar <ArrowRight size={18} /></Link><Link href="#how-it-works" className="button button-outline">See how it works <ArrowUpRight size={18} /></Link></div><div className="hero-footnote"><Check size={17} /><span>Personalized to your goals, skills, and season of life.</span></div></div>
      <div className="radar-hero-visual"><div className="radar-glow" /><div className="radar-scan" /><div className="radar-card radar-card-main"><div className="radar-card-head"><span className="radar-icon"><Sparkles size={18} /></span><span><small>YOUR RADAR</small><strong>Fresh matches for you</strong></span><Bell size={17} /></div><div className="match-item"><span className="match-logo match-purple">AU</span><div><strong>Access University Scholarship</strong><small>92% match · Deadline in 12 days</small></div><Bookmark size={17} /></div><div className="match-item"><span className="match-logo match-orange">GC</span><div><strong>Graduate Catalyst Program</strong><small>86% match · Opens this week</small></div><Bookmark size={17} /></div><div className="match-item"><span className="match-logo match-blue">F</span><div><strong>Future Makers Fellowship</strong><small>81% match · Apply by 24 Oct</small></div><Bookmark size={17} /></div><Link className="radar-see-all" href="/register">View all matches <ArrowRight size={15} /></Link></div><div className="radar-pill radar-pill-top"><span className="pill-dot" /> 14 new matches</div><div className="radar-pill radar-pill-bottom"><CalendarClock size={16} /> 3 deadlines this week</div></div>
    </section>
    <div className="radar-proof"><div className="landing-container"><span><Search size={17} /> Less searching</span><span><Target size={17} /> Better-fit opportunities</span><span><CalendarClock size={17} /> No missed deadlines</span></div></div>
    <section className="radar-section landing-container" id="opportunities"><div className="radar-section-heading"><div><span className="landing-eyebrow">MORE THAN A JOB BOARD</span><h2>One place for<br /><em>what’s next.</em></h2></div><p>Big goals rarely fit into one category. GetNeba keeps the full landscape of possibilities in view.</p></div><div className="opportunity-grid">{opportunityTypes.map(({ icon: Icon, label, copy }) => <Link href="/register" className="opportunity-card" key={label}><span className="opportunity-icon"><Icon size={24} /></span><span className="card-arrow"><ArrowUpRight size={18} /></span><h3>{label}</h3><p>{copy}</p></Link>)}</div></section>
    <section className="radar-how" id="how-it-works"><div className="landing-container"><div className="radar-how-intro"><span className="landing-eyebrow">A SMARTER WAY TO SEARCH</span><h2>Less noise.<br /><em>More momentum.</em></h2><p>Tell us what you are working toward. GetNeba helps you see the opportunities worth your attention.</p><Link className="section-link" href="/register">Start your profile <ArrowRight size={17} /></Link></div><div className="radar-steps"><article><span className="radar-step-number">01</span><div><h3>Tell us your direction.</h3><p>Share your education, experience, skills, interests, and the goal you are chasing.</p></div></article><article><span className="radar-step-number">02</span><div><h3>Get your best-fit radar.</h3><p>We surface relevant opportunities and explain what makes each one worth a closer look.</p></div></article><article><span className="radar-step-number">03</span><div><h3>Move before the deadline.</h3><p>Save the ones you like, track what is due, and keep your applications moving.</p></div></article></div></div></section>
    <section className="radar-match landing-container"><div className="match-orbit" aria-hidden="true"><div className="orbit-line orbit-line-one" /><div className="orbit-line orbit-line-two" /><span className="orbit-node node-one"><GraduationCap size={17} /></span><span className="orbit-node node-two"><UsersRound size={17} /></span><span className="orbit-node node-three"><TrendingUp size={17} /></span><div className="orbit-core"><Compass size={38} /><small>YOUR<br />RADAR</small></div></div><div className="radar-match-copy"><span className="landing-eyebrow">WHY PERSONALIZATION MATTERS</span><h2>Opportunity is personal.</h2><p>The right opportunity depends on more than a keyword. GetNeba connects the dots between where you are, what you can do, and where you want to go.</p><div className="match-list"><span><Check size={16} /> Your goals shape what you see</span><span><Check size={16} /> Every match comes with context</span><span><Check size={16} /> Your shortlist stays yours</span></div><Link className="button button-dark" href="/register">Create my free radar <ArrowUpRight size={17} /></Link></div></section>
    <section className="radar-cta landing-container"><div><span className="landing-eyebrow">THE NEXT YES COULD BE CLOSER</span><h2>Stop hoping you find it.<br /><em>Start knowing where to look.</em></h2><p>Build your profile once. Let GetNeba keep watch.</p></div><Link className="button button-dark" href="/register">Get started free <ArrowRight size={18} /></Link></section>
  </main>;
}
