import Link from "next/link";
import { ArrowRight, ArrowUpRight, BadgeCheck, Banknote, Bot, Check, ChevronRight, Clock3, FileText, MapPin, MessageCircleMore, PhoneCall, ShieldCheck, Sparkles, UserRoundCheck, Wrench } from "lucide-react";
import { jsonLd, publicPageMetadata, siteDescription, siteUrl } from "@/lib/seo";

const proof = [
  ["01", "Capture every enquiry", "Turn a WhatsApp message, voice note or photo into a job that cannot get lost."],
  ["02", "Keep the work moving", "Send a quote, take a deposit and assign the right person before the customer has to ask twice."],
  ["03", "Close with confidence", "Share proof of work, collect the balance and bring the customer back when they need you again."],
];
const outcomes = ["One place for WhatsApp jobs, customers and crews", "A professional job tracker your customers can open without an app", "Clear deposits, balances and jobs that still need attention"];
export const metadata = publicPageMetadata("Neba Pro — turn WhatsApp enquiries into paid jobs", siteDescription, "/");

export default function LandingPage() {
  return <main className="pro-page" id="main-content">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd({ "@context": "https://schema.org", "@graph": [{ "@type": "Organization", "@id": new URL("/#organization", siteUrl).toString(), name: "Neba", url: siteUrl.toString(), description: siteDescription }, { "@type": "SoftwareApplication", name: "Neba Pro", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: siteDescription }] }) }} />
    <section className="pro-hero pro-wrap">
      <div className="pro-hero-copy"><div className="pro-kicker"><span className="pro-pulse" /> BUILT FOR SERVICE BUSINESSES ON THE MOVE</div><h1>Every WhatsApp enquiry.<br /><em>A paid job.</em></h1><p>Neba gives service businesses one calm place to quote, schedule, assign, prove and collect—without asking customers to download another app.</p><div className="pro-actions"><Link className="pro-button pro-button-primary" href="/register">Start with Neba Pro <ArrowUpRight size={18} /></Link><a className="pro-text-link" href="#workspace">See the workflow <ArrowRight size={17} /></a></div><div className="pro-trust-line"><span><BadgeCheck size={17} /> Made for teams in Nigeria</span><span><Banknote size={17} /> Prices in naira</span></div></div>
      <div className="pro-job-stage" aria-label="Example Neba Pro job workspace"><div className="stage-grid" /><div className="stage-topline"><span>LIVE JOB VIEW</span><span className="stage-live"><i /> Updated now</span></div><article className="stage-job-card"><div className="stage-job-top"><span className="stage-job-icon"><Wrench size={22} /></span><span className="stage-pill">CONFIRMED</span><button aria-label="More job options">•••</button></div><h2>AC isn’t cooling</h2><p><MapPin size={15} /> Lekki Phase 1 · Today, 2:00 PM</p><div className="stage-progress"><span className="done"><Check size={12} /> Request</span><span className="done"><Check size={12} /> Quote</span><span className="current">On the way</span><span>Done</span></div><div className="stage-agent"><span><UserRoundCheck size={18} /><b>Assigned to</b></span><strong>Ibrahim A.</strong></div></article><div className="stage-note stage-note-one"><MessageCircleMore size={17} /><span><b>New enquiry</b><small>Voice note captured</small></span></div><div className="stage-note stage-note-two"><Banknote size={17} /><span><b>₦15,000 deposit</b><small>Paid by customer</small></span></div></div>
    </section>
    <section className="pro-rail"><div className="pro-wrap"><span>FOR AC TECHNICIANS</span><i /><span>FOR CLEANING TEAMS</span><i /><span>FOR ELECTRICIANS</span><i /><span>FOR HOME SERVICES</span><i /><span>FOR REPAIR CREWS</span></div></section>
    <section className="pro-problem pro-wrap"><div><div className="pro-kicker">THE JOB SHOULD NOT GET LOST IN THE CHAT</div><h2>Small teams do serious work.<br />Their tools should too.</h2></div><p>Your customer starts in WhatsApp. Your technician is on the road. Your payment comes by transfer. Neba connects the parts in between, so the owner knows exactly what needs attention.</p></section>
    <section className="pro-workspace" id="workspace"><div className="pro-wrap"><div className="pro-section-heading"><div><div className="pro-kicker">THE NEBA WORKSPACE</div><h2>One clear next step<br />for every job.</h2></div><p>A visual job pipeline designed for real service work—not generic admin software.</p></div><div className="pro-workspace-card"><div className="workspace-bar"><div className="workspace-logo"><span>N</span> Neba <b>PRO</b></div><div><span className="workspace-date">Tuesday, 03 Oct</span><button>+ New job</button></div></div><div className="workspace-content"><aside className="workspace-side"><span className="workspace-label">WORKSPACE</span><a className="active"><FileText size={17} /> Jobs <b>12</b></a><a><MessageCircleMore size={17} /> Inbox <b>3</b></a><a><UserRoundCheck size={17} /> Customers</a><a><Banknote size={17} /> Payments</a><div className="workspace-ai"><Sparkles size={16} /><strong>Today’s focus</strong><p>3 jobs need a reply before they go cold.</p><a>Review jobs <ChevronRight size={14} /></a></div></aside><div className="workspace-board"><div className="board-title"><div><span className="workspace-label">JOBS</span><h3>Today’s work</h3></div><span className="board-count">12 open jobs</span></div><div className="board-columns"><JobColumn name="New request" count="3" accent="orange"><Job title="Washing machine leaking" customer="Chioma O." meta="New message · 12 mins ago" /></JobColumn><JobColumn name="Quote sent" count="2" accent="yellow"><Job title="Install 2 split units" customer="Dami B." meta="₦42,000 · Awaiting approval" /></JobColumn><JobColumn name="In progress" count="4" accent="green"><Job title="AC isn’t cooling" customer="Emeka N." meta="Ibrahim is on the way" live /></JobColumn><JobColumn name="Ready to collect" count="3" accent="blue"><Job title="Deep clean, 3-bedroom" customer="Amara E." meta="₦18,000 balance due" due /></JobColumn></div></div></div></div></div></section>
    <section className="pro-flow pro-wrap" id="how-it-works"><div className="pro-flow-intro"><div className="pro-kicker">HOW THE WORK FLOWS</div><h2>Built around the way<br />your work actually moves.</h2><p>Not another calendar. A shared record of each customer job, from first message to final payment.</p><Link href="/register" className="pro-button pro-button-dark">Set up your workspace <ArrowRight size={18} /></Link></div><div className="pro-flow-list">{proof.map(([number, title, copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div><ArrowUpRight size={19} /></article>)}</div></section>
    <section className="pro-ai"><div className="pro-wrap pro-ai-grid"><div><div className="pro-kicker"><Sparkles size={15} /> NEBA ASSIST</div><h2>AI that clears the work,<br />not just the conversation.</h2><p>Neba Assist turns the messages your team already receives into the next useful action. You stay in control of every customer promise and price.</p><Link href="/register" className="pro-text-link">Meet Neba Assist <ArrowRight size={17} /></Link></div><div className="ai-list"><article><Bot size={21} /><div><h3>Voice note → job card</h3><p>Capture service, location, timing and photos without typing it all again.</p></div></article><article><PhoneCall size={21} /><div><h3>Faster first response</h3><p>Answer approved service questions and hand unusual jobs straight to your team.</p></div></article><article><Clock3 size={21} /><div><h3>Money-at-risk alert</h3><p>See forgotten quotes, overdue balances and quiet customers before revenue leaks.</p></div></article></div></div></section>
    <section className="pro-close pro-wrap"><div><div className="pro-kicker">YOUR BUSINESS, IN CONTROL</div><h2>Stop chasing chats.<br /><em>Start running the job.</em></h2></div><div><ul>{outcomes.map((outcome) => <li key={outcome}><ShieldCheck size={18} />{outcome}</li>)}</ul><Link href="/register" className="pro-button pro-button-primary">Start building your workspace <ArrowUpRight size={18} /></Link></div></section>
  </main>;
}
function JobColumn({ name, count, accent, children }: { name: string; count: string; accent: string; children: React.ReactNode }) { return <section className={`job-column ${accent}`}><div className="job-column-title"><span>{name}</span><b>{count}</b></div>{children}<button className="job-add">+</button></section>; }
function Job({ title, customer, meta, live, due }: { title: string; customer: string; meta: string; live?: boolean; due?: boolean }) { return <article className="board-job"><div className="board-job-icon"><Wrench size={15} /></div><h4>{title}</h4><p>{customer}</p><small className={due ? "due" : ""}>{live && <i />} {meta}</small></article>; }
