"use client";

import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Compass, MapPin, Sparkles } from "lucide-react";
import { api } from "@/lib/api";
import { User } from "@/lib/types";

const intents = ["Work", "Learn", "Build", "Fund", "Explore"].map((label) => ({ value: label.toLowerCase(), label }));
const interestAreas = ["Software & technology", "Business", "Finance", "Design", "Engineering", "Marketing", "Healthcare", "Education", "Creative work", "Agriculture", "Social impact"].map((label) => ({ value: label.toLowerCase().replaceAll(" ", "-"), label }));
const legacyValues: Record<string, string> = { Scholarships: "scholarship", Grants: "grant", Jobs: "work", Internships: "internship", Fellowships: "fellowship", Competitions: "competition", Training: "learn", "Startup programs": "build", "Business funding": "fund", "Remote opportunities": "remote", "Fund my education": "fund", "Find a job": "work", "Start or grow a business": "build", "Learn a skill": "learn", "Get international opportunities": "explore", "Get funding": "fund" };
function normalize(values: string[] = []) { return values.map((value) => legacyValues[value] || value); }

function ChoiceGrid({ options, selected, onChange }: { options: { value: string; label: string }[]; selected: string[]; onChange: (values: string[]) => void }) {
  return <div className="onboarding-choice-grid">{options.map(({ value, label }) => { const active = selected.includes(value); return <button type="button" key={value} className={active ? "active" : ""} aria-pressed={active} onClick={() => onChange(active ? selected.filter((item) => item !== value) : [...selected, value])}><span aria-hidden="true">{active && <Check size={14} />}</span>{label}</button>; })}</div>;
}

export function OnboardingForm({ initialUser, nextPath }: { initialUser: User; nextPath?: string }) {
  const [user, setUser] = useState(initialUser); const [step, setStep] = useState<1 | 2 | 3 | 4>(1);
  const [selectedIntents, setSelectedIntents] = useState(normalize(initialUser.goals)); const [selectedAreas, setSelectedAreas] = useState(normalize(initialUser.opportunity_interests));
  const [remote, setRemote] = useState(selectedAreas.includes("remote") ? "yes" : ""); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState("");
  async function save(payload: Record<string, unknown>) { const updated = await api<User>("/auth/me/", { method: "PATCH", body: JSON.stringify(payload) }); setUser(updated); return updated; }
  async function submitIntents(event: FormEvent) { event.preventDefault(); if (!selectedIntents.length) { setFeedback("Choose at least one direction to get started."); return; } setBusy(true); setFeedback(""); try { await save({ goals: selectedIntents }); setStep(2); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function submitAreas(event: FormEvent) { event.preventDefault(); if (!selectedAreas.length) { setFeedback("Pick at least one area so we can personalize your opportunities."); return; } setBusy(true); setFeedback(""); try { await save({ opportunity_interests: selectedAreas }); setStep(3); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  async function submitLocation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setFeedback(""); const data = Object.fromEntries(new FormData(event.currentTarget)); const areas = selectedAreas.filter((area) => area !== "remote"); if (remote === "yes") areas.push("remote"); try { await save({ country: data.country, state: data.state, opportunity_interests: areas }); setStep(4); } catch (error) { setFeedback((error as Error).message); } finally { setBusy(false); } }
  function finish() { window.location.assign(nextPath && nextPath.startsWith("/") && !nextPath.startsWith("//") ? nextPath : "/dashboard"); }
  return <main className="opportunity-onboarding onboarding-light container"><div className="onboarding-topline"><div><span className="eyebrow">MAKE GETNEBA YOURS</span><small>{step < 4 ? `A few quick choices · ${step} of 3` : "Your radar is ready"}</small></div><div className="onboarding-progress" role="progressbar" aria-label="Onboarding progress" aria-valuemin={1} aria-valuemax={3} aria-valuenow={Math.min(step, 3)}>{[1, 2, 3].map((item) => <span className={step >= item ? "active" : ""} key={item} />)}</div></div>{step < 4 && <button className="onboarding-back" type="button" onClick={() => setStep((Math.max(1, step - 1) as 1 | 2 | 3 | 4))} disabled={step === 1}><ArrowLeft size={15} /> Back</button>}
    {step === 1 && <section className="opportunity-onboarding-card onboarding-step-card step-enter"><span className="profile-icon"><Compass size={22} /></span><span className="landing-eyebrow">START WITH YOUR DIRECTION</span><h1>What are you here to do?</h1><p>Choose as many as you like. We’ll use this to shape what you see first.</p><form onSubmit={submitIntents}><ChoiceGrid options={intents} selected={selectedIntents} onChange={setSelectedIntents} />{feedback && <p className="error-box" role="alert">{feedback}</p>}<button className="button button-dark" disabled={busy}>{busy ? "Saving…" : "Continue"}<ArrowRight size={17} /></button></form></section>}
    {step === 2 && <section className="opportunity-onboarding-card onboarding-step-card step-enter"><span className="profile-icon"><Sparkles size={22} /></span><span className="landing-eyebrow">PERSONALIZE YOUR RADAR</span><h1>What are you interested in?</h1><p>Pick a few areas so we can bring the right opportunities closer to you.</p><form onSubmit={submitAreas}><ChoiceGrid options={interestAreas} selected={selectedAreas} onChange={setSelectedAreas} />{feedback && <p className="error-box" role="alert">{feedback}</p>}<button className="button button-dark" disabled={busy}>{busy ? "Saving…" : "Continue"}<ArrowRight size={17} /></button></form></section>}
    {step === 3 && <section className="opportunity-onboarding-card onboarding-step-card step-enter"><span className="profile-icon"><MapPin size={22} /></span><span className="landing-eyebrow">A LITTLE CONTEXT</span><h1>Where are you based?</h1><p>This helps us show opportunities you’re eligible for. Your location stays in your profile.</p><form className="onboarding-location-form" onSubmit={submitLocation}><label>Country<select name="country" defaultValue={user.country || "Nigeria"} required><option>Nigeria</option><option>Ghana</option><option>Kenya</option><option>South Africa</option><option>United Kingdom</option><option>United States</option><option>Other</option></select></label><label>City or state <small>Optional</small><input name="state" defaultValue={user.state || ""} placeholder="e.g. Lagos" /></label><fieldset><legend>Are you open to remote opportunities?</legend><div className="onboarding-radio-row">{[["yes", "Yes"], ["no", "No"]].map(([value, label]) => <label key={value} className={remote === value ? "active" : ""}><input type="radio" name="remote" value={value} checked={remote === value} onChange={() => setRemote(value)} />{label}</label>)}</div></fieldset>{feedback && <p className="error-box" role="alert">{feedback}</p>}<button className="button button-dark" disabled={busy}>{busy ? "Saving…" : "Continue"}<ArrowRight size={17} /></button></form></section>}
    {step === 4 && <section className="opportunity-onboarding-card onboarding-ready-card step-enter"><span className="ready-mark"><Check size={25} /></span><span className="landing-eyebrow">YOUR RADAR IS READY</span><h1>You’re ready to explore.</h1><p>We’ve started building your opportunity feed. You can add more information to your profile anytime to improve your matches.</p><div className="ready-summary"><span>{selectedIntents.length} direction{selectedIntents.length === 1 ? "" : "s"} chosen</span><span>{selectedAreas.length} interest{selectedAreas.length === 1 ? "" : "s"} added</span><span>{user.country || "Nigeria"}</span></div><button className="button button-dark" onClick={finish}>Explore opportunities <ArrowRight size={17} /></button><button className="ready-profile-link" type="button" onClick={finish}>I’ll add more later</button></section>}
  </main>;
}
