"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowRight, Bookmark, CalendarClock, Check, ChevronDown, Filter, Search, Sparkles } from "lucide-react";
import { api } from "@/lib/api";
import { Opportunity, Page } from "@/lib/types";
import { opportunityPath } from "@/lib/routes";

const labels: Record<string, string> = { scholarship: "Scholarship", grant: "Grant", job: "Job", internship: "Internship", fellowship: "Fellowship", competition: "Competition", training: "Training", startup: "Startup program", funding: "Funding", tender: "Tender", remote: "Remote" };
const intentCategories: Record<string, string[]> = { all: [], work: ["job", "internship", "remote"], learn: ["scholarship", "fellowship", "training"], build: ["startup", "competition", "tender"], fund: ["grant", "funding"] };
const intents = ["all", "work", "learn", "build", "fund"];
const deadline = (value: string | null) => value ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "No deadline listed";
const location = (item: Opportunity) => item.is_remote ? "Remote" : item.location_label || item.country || "Open location";
const daysUntil = (value: string | null) => value ? Math.ceil((new Date(value).getTime() - Date.now()) / 86400000) : null;

function OpportunityCard({ item, onSave }: { item: Opportunity; onSave: (item: Opportunity) => void }) {
  return <article className="opportunity-card opportunity-card-reframed">
    <div className="opportunity-card-top"><span className="opportunity-type">{labels[item.category] || item.category}</span>{item.match && <strong className="opportunity-match">{item.match.score}% profile fit</strong>}</div>
    <h3>{item.title}</h3><p className="opportunity-provider">{item.provider} · {item.is_remote ? "Remote" : labels[item.category] || item.category}</p>
    <p className="opportunity-summary">{item.summary}</p>
    <div className="opportunity-meta"><span>{item.benefit || labels[item.category]}</span><span>{location(item)}</span></div>
    <div className="opportunity-deadline"><CalendarClock size={15} /><span><small>{item.deadline && daysUntil(item.deadline) !== null && daysUntil(item.deadline)! <= 14 ? "Closes" : "Deadline"}</small>{deadline(item.deadline)}</span></div>
    {item.match?.reasons.length ? <div className="opportunity-card-reasons"><small>Why you match</small>{item.match.reasons.slice(0, 2).map((reason) => <span key={reason}><Check size={13} />{reason}</span>)}</div> : null}
    <footer><button className={`opportunity-save${item.saved_status ? " saved" : ""}`} onClick={() => onSave(item)} aria-label={item.saved_status ? "Remove saved opportunity" : "Save opportunity"}><Bookmark size={16} fill={item.saved_status ? "currentColor" : "none"} />{item.saved_status ? "Saved" : "Save"}</button><Link className="opportunity-view" href={opportunityPath(item.title, item.public_id)}>View opportunity <ArrowRight size={15} /></Link></footer>
  </article>;
}

export function OpportunityList({ matches = false }: { matches?: boolean }) {
  const [items, setItems] = useState<Opportunity[]>([]); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [hasMore, setHasMore] = useState(false); const [page, setPage] = useState(1); const [query, setQuery] = useState(""); const [activeIntent, setActiveIntent] = useState("all"); const [filtersOpen, setFiltersOpen] = useState(false); const [remoteOnly, setRemoteOnly] = useState(false); const [locationQuery, setLocationQuery] = useState(""); const [deadlineFilter, setDeadlineFilter] = useState("all"); const [typeFilter, setTypeFilter] = useState("");
  const loadMoreRef = useRef<HTMLDivElement | null>(null); const endpoint = matches ? "/opportunities/matches/" : "/opportunities/";
  const loadPage = useCallback(async (pageNumber: number, replace = false) => { if (replace) setLoading(true); else setLoadingMore(true); try { const result = await api<Page<Opportunity>>(`${endpoint}?page=${pageNumber}`); setItems((current) => replace ? result.results : [...current, ...result.results.filter((item) => !current.some((existing) => existing.public_id === item.public_id))]); setPage(pageNumber); setHasMore(Boolean(result.next)); } catch (error) { if (replace) setItems([]); else console.error("Could not load more opportunities", error); } finally { if (replace) setLoading(false); else setLoadingMore(false); } }, [endpoint]);
  useEffect(() => { void loadPage(1, true); }, [loadPage]);
  useEffect(() => { const target = loadMoreRef.current; if (!target || !hasMore) return; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && !loading && !loadingMore) void loadPage(page + 1); }, { rootMargin: "600px 0px" }); observer.observe(target); return () => observer.disconnect(); }, [hasMore, loading, loadingMore, page, loadPage]);
  const visible = items.filter((item) => { const haystack = `${item.title} ${item.provider} ${item.category} ${item.summary} ${item.benefit} ${item.country} ${item.location_label}`.toLowerCase(); const matchesSearch = haystack.includes(query.toLowerCase()); const categoryMatches = activeIntent === "all" || intentCategories[activeIntent].includes(item.category); const matchesType = !typeFilter || item.category === typeFilter; const matchesLocation = !locationQuery.trim() || `${item.country} ${item.location_label} ${item.is_remote ? "remote" : ""}`.toLowerCase().includes(locationQuery.trim().toLowerCase()); const days = daysUntil(item.deadline); const matchesDeadline = deadlineFilter === "all" || (days !== null && days >= 0 && days <= Number(deadlineFilter)); return matchesSearch && categoryMatches && matchesType && matchesLocation && matchesDeadline && (!remoteOnly || item.is_remote); });
  const recommended = visible.filter((item) => item.match).sort((a, b) => (b.match?.score || 0) - (a.match?.score || 0)).slice(0, 3); const remaining = visible.filter((item) => !recommended.some((match) => match.public_id === item.public_id)); const closingSoon = visible.filter((item) => { const days = daysUntil(item.deadline); return days !== null && days >= 0 && days <= 14; }).sort((a, b) => (daysUntil(a.deadline) || 99) - (daysUntil(b.deadline) || 99)).slice(0, 3);
  function save(item: Opportunity) { const saved = Boolean(item.saved_status); api(`/opportunities/${item.public_id}/save/`, { method: saved ? "DELETE" : "POST", body: JSON.stringify({}) }).then(() => setItems((current) => current.map((row) => row.public_id === item.public_id ? { ...row, saved_status: saved ? null : "saved" } : row))).catch(() => {}); }
  function promptSearch(value: string) { setQuery(value); setActiveIntent("all"); }

  return <main className="opportunity-list-page opportunity-discover-page container">
    <header className="opportunity-page-header opportunity-discover-header"><div><span className="eyebrow">YOUR OPPORTUNITY RADAR</span><h1>Discover opportunities</h1><p>Find things worth pursuing — from work and funding to learning, building, and collaboration.</p></div><Link className="button button-outline" href="/my-opportunities/new">+ Post an opportunity</Link></header>
    <div className="opportunity-search-row"><div className="opportunity-list-search"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search opportunities, skills, organizations..." aria-label="Search opportunities" /></div><button className={`opportunity-filter-button${filtersOpen ? " active" : ""}`} onClick={() => setFiltersOpen((open) => !open)}><Filter size={16} /> Filters <ChevronDown size={15} /></button></div>
    <nav className="opportunity-tabs opportunity-intent-tabs" aria-label="Opportunity goals">{intents.map((intent) => <button key={intent} className={activeIntent === intent ? "active" : ""} onClick={() => setActiveIntent(intent)}>{intent === "all" ? "All" : intent[0].toUpperCase() + intent.slice(1)}</button>)}</nav>
    {filtersOpen && <div className="opportunity-filter-panel"><label>Location<input value={locationQuery} onChange={(event) => setLocationQuery(event.target.value)} placeholder="Any location" /></label><label>Deadline<select value={deadlineFilter} onChange={(event) => setDeadlineFilter(event.target.value)}><option value="all">Any deadline</option><option value="7">Next 7 days</option><option value="30">Next 30 days</option><option value="90">Next 90 days</option></select></label><label>Opportunity type<select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="">All types</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="opportunity-toggle"><input type="checkbox" checked={remoteOnly} onChange={(event) => setRemoteOnly(event.target.checked)} /> Remote only</label></div>}
    <section className="opportunity-what-can-i-do"><div><span className="eyebrow">NOT SURE WHAT TO LOOK FOR?</span><h2>Tell us what you’re trying to achieve.</h2></div><div className="opportunity-prompt-chips"><button onClick={() => promptSearch("fund my startup")}>Fund my startup</button><button onClick={() => promptSearch("Nigerian software developer")}>For a Nigerian software developer</button><button onClick={() => promptSearch("gain experience")}>Gain experience</button><button onClick={() => promptSearch("technical co-founder")}>Find a technical co-founder</button></div></section>
    {loading ? <div className="dashboard-loading">Loading opportunities...</div> : visible.length ? <>{recommended.length > 0 && <section className="opportunity-recommended"><div className="opportunity-section-heading"><div><span className="eyebrow">BASED ON YOUR PROFILE</span><h2>Recommended for you</h2><p>These opportunities line up with your interests, profile, and previous activity.</p></div><Sparkles size={24} /></div><div className="opportunity-card-grid">{recommended.map((item) => <OpportunityCard key={item.public_id} item={item} onSave={save} />)}</div></section>}{closingSoon.length > 0 && <section className="opportunity-closing-soon"><div className="opportunity-section-heading compact"><div><span className="eyebrow">DON’T MISS THE WINDOW</span><h2>Closing soon</h2><p>Opportunities worth checking before their deadline passes.</p></div></div><div className="opportunity-closing-list">{closingSoon.map((item) => <Link href={opportunityPath(item.title, item.public_id)} key={item.public_id}><div><strong>{item.title}</strong><span>{labels[item.category] || item.category} · {item.is_remote ? "Remote" : location(item)}</span></div><b>{daysUntil(item.deadline) === 0 ? "Closes today" : `Closes in ${daysUntil(item.deadline)} days`} <ArrowRight size={14} /></b></Link>)}</div></section>}<section className="opportunity-results"><div className="opportunity-section-heading compact"><div><span className="eyebrow">KEEP EXPLORING</span><h2>{activeIntent === "all" ? "More opportunities" : `${activeIntent[0].toUpperCase() + activeIntent.slice(1)} opportunities`}</h2></div><span className="opportunity-result-count">{visible.length} found</span></div><div className="opportunity-card-grid">{remaining.map((item) => <OpportunityCard key={item.public_id} item={item} onSave={save} />)}</div></section><div ref={loadMoreRef} className={`opportunity-load-more${loadingMore ? " loading" : ""}`} aria-live="polite">{loadingMore ? "Finding more opportunities…" : hasMore ? "Scroll to load more" : "You’ve reached the end."}</div></> : <div className="radar-empty"><Sparkles size={26} /><div><strong>{matches ? "No matches yet" : "No opportunities found"}</strong><p>{matches ? "Complete more of your profile or check back when new opportunities are added." : "Try a different search or filter."}</p></div></div>}
  </main>;
}
