from datetime import UTC, datetime

from django.core.management.base import BaseCommand
from django.db import transaction

from opportunities.models import Opportunity


AFRICAN_COUNTRIES = [
    "Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde",
    "Cameroon", "Central African Republic", "Chad", "Comoros", "Côte d’Ivoire",
    "Democratic Republic of the Congo", "Djibouti", "Egypt", "Equatorial Guinea",
    "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea",
    "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi",
    "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger",
    "Nigeria", "Republic of the Congo", "Rwanda", "São Tomé and Príncipe", "Senegal",
    "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan",
    "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe",
]

EU_EEA_COUNTRIES = [
    "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark",
    "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland",
    "Ireland", "Italy", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta",
    "Netherlands", "Norway", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia",
    "Spain", "Sweden",
]


def deadline(year, month, day, hour=23, minute=59):
    return datetime(year, month, day, hour, minute, tzinfo=UTC)


ROWS = [
    {
        "title": "International Scholars Program 2027",
        "provider": "University of British Columbia",
        "summary": "Need-and-merit awards for international students entering their first undergraduate degree at UBC. The program looks for excellent academic performance, leadership, community contribution, and significant financial need.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Need-based funding toward study and living costs",
        "deadline": deadline(2026, 11, 15),
        "country": "Canada",
        "location_label": "Vancouver, Canada",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["secondary"],
        "fields_of_study": [],
        "employment_statuses": ["student"],
        "eligibility_notes": "For international students entering directly from secondary school for their first undergraduate degree. A school or nonprofit nomination is required, and applicants must show significant financial need.",
        "application_url": "https://you.ubc.ca/financial-planning/scholarships-awards-international-students/international-scholars/",
    },
    {
        "title": "Lester B. Pearson International Scholarship 2027",
        "provider": "University of Toronto",
        "summary": "A four-year scholarship for exceptional international secondary-school students who demonstrate academic achievement, creativity, and leadership within their school and community.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Tuition, books, incidental fees and residence for four years",
        "deadline": deadline(2026, 11, 6),
        "country": "Canada",
        "location_label": "Toronto, Canada",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["secondary"],
        "fields_of_study": [],
        "employment_statuses": ["student"],
        "eligibility_notes": "Applicants must be international students in their final year of secondary school, or have graduated no earlier than June 2026, and begin at U of T in September 2027. School nomination is required; nomination and admission deadlines come before the scholarship deadline.",
        "application_url": "https://future.utoronto.ca/pearson-scholarships",
    },
    {
        "title": "Mastercard Foundation Scholars Program 2027",
        "provider": "University of British Columbia",
        "summary": "Graduate scholarships for academically talented young people from Africa who have limited access to higher education and are committed to leadership and community impact.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Comprehensive graduate scholarship and scholar support",
        "deadline": deadline(2026, 11, 20),
        "country": "Canada",
        "location_label": "Vancouver, Canada",
        "eligible_countries": AFRICAN_COUNTRIES,
        "education_levels": ["university"],
        "fields_of_study": ["Forestry", "Land and Food Systems", "Science", "Business", "Public Policy"],
        "employment_statuses": ["student", "employed", "unemployed", "self_employed"],
        "max_age": 35,
        "eligibility_notes": "Applicants must be citizens or refugees of an African country, hold a bachelor's degree, be 35 or younger, and not already hold a master's degree. Only listed UBC master's programs qualify; follow the program's staged application instructions.",
        "application_url": "https://mastercardfdn.scholars.ubc.ca/graduate-admissions/graduate-admissions-2/",
    },
    {
        "title": "Undergraduate International Excellence Scholarships 2027",
        "provider": "Cardiff University",
        "summary": "Merit awards for international students who will begin an eligible undergraduate degree at Cardiff University in 2027.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Nine awards of £10,000",
        "deadline": deadline(2027, 4, 2),
        "country": "United Kingdom",
        "location_label": "Cardiff, Wales",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["secondary"],
        "fields_of_study": [],
        "employment_statuses": ["student"],
        "eligibility_notes": "For self-funded international students holding an offer for an eligible undergraduate course beginning in 2027. Eligible offer holders receive application instructions from Cardiff University.",
        "application_url": "https://www.cardiff.ac.uk/study/international/funding-and-fees/international-scholarships/undergraduate-excellence-scholarships",
    },
    {
        "title": "Undergraduate Scholars Entrance Scholarships 2027",
        "provider": "Simon Fraser University",
        "summary": "Entrance scholarships for new high-school applicants with strong academic results and sustained leadership or community contribution.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Major entrance scholarship toward an SFU undergraduate degree",
        "deadline": deadline(2026, 12, 16, 7, 59),
        "country": "Canada",
        "location_label": "British Columbia, Canada",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["secondary"],
        "fields_of_study": [],
        "employment_statuses": ["student"],
        "eligibility_notes": "Open to domestic and international high-school applicants. Applicants normally need at least 90% or 31 IB points and evidence of community or school leadership. The scholarship application closes 15 December 2026 at 11:59 p.m. Pacific; references and admission documents are due 31 January 2027.",
        "application_url": "https://www.sfu.ca/students/financial-aid/entrance/highschool/uses.html",
    },
    {
        "title": "Clarendon Scholarships 2027–28",
        "provider": "University of Oxford",
        "summary": "Oxford's major graduate scholarship scheme awards fully funded places based on academic excellence and future potential across eligible master's and doctoral courses.",
        "category": Opportunity.Category.SCHOLARSHIP,
        "benefit": "Full course fees and a living-cost grant",
        "deadline": None,
        "country": "United Kingdom",
        "location_label": "Oxford, United Kingdom",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["university", "masters"],
        "fields_of_study": [],
        "employment_statuses": ["student", "employed", "unemployed", "self_employed"],
        "eligibility_notes": "All nationalities and eligible graduate subjects are considered automatically when the Oxford course application is submitted by that course's December 2026 or January 2027 funding deadline. There is no separate Clarendon form.",
        "application_url": "https://www.ox.ac.uk/admissions/graduate/fees-and-funding/funding/clarendon/applicants",
    },
    {
        "title": "Global Health Virtual Fellowship — February 2027",
        "provider": "NHS England Global Health Partnerships",
        "summary": "A virtual professional-development fellowship that supports participants to contribute their skills to global health partnerships while learning through structured collaboration.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Virtual fellowship, induction and global-health experience",
        "deadline": deadline(2026, 11, 1, 23, 59),
        "country": "United Kingdom",
        "location_label": "Virtual",
        "is_remote": True,
        "eligible_countries": ["United Kingdom"],
        "education_levels": ["university", "masters", "phd"],
        "fields_of_study": ["Medicine", "Public Health", "Health Sciences", "Nursing", "Management"],
        "employment_statuses": ["employed"],
        "eligibility_notes": "Applicants should confirm the NHS workforce and professional eligibility in the official FAQ. Successful applicants must attend both mandatory online induction mornings in January 2027.",
        "application_url": "https://global.hee.nhs.uk/supporting-individuals/global-fellowships/recruitment/",
    },
    {
        "title": "Public Health Informatics Fellowship Program — Class of 2027",
        "provider": "U.S. Centers for Disease Control and Prevention",
        "summary": "A two-year, full-time fellowship combining public health practice with data, information systems, and informatics assignments at CDC and partner sites.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Two-year paid public-health informatics fellowship",
        "deadline": deadline(2026, 11, 7, 4, 59),
        "country": "United States",
        "location_label": "United States · Placement based",
        "eligible_countries": ["United States"],
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["Public Health", "Health Informatics", "Computer Science", "Medicine", "Data Science"],
        "employment_statuses": ["employed", "unemployed"],
        "eligibility_notes": "Applicants must meet the CDC's detailed education, informatics, public-health, and research experience requirements, commit full time for two years, and be willing to relocate to the assignment site.",
        "application_url": "https://www.cdc.gov/phifp/php/participants/index.html",
    },
    {
        "title": "Internet Society Fellowship Program 2027",
        "provider": "Internet Society",
        "summary": "A global fellowship for people working on practical projects that strengthen an open, globally connected, secure, and trustworthy Internet.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Mentorship, up to US$5,000 project stipend and travel support",
        "deadline": deadline(2026, 11, 22),
        "country": "Global",
        "location_label": "Global · Remote with supported travel",
        "is_remote": True,
        "eligible_countries": ["Worldwide"],
        "education_levels": ["university", "masters", "phd", "other"],
        "fields_of_study": ["Computer Science", "Information Technology", "Cybersecurity", "Public Policy", "Law", "Social Sciences"],
        "employment_statuses": ["student", "employed", "unemployed", "self_employed", "freelancer"],
        "eligibility_notes": "Enrollment and all required self-paced pre-fellowship modules must be completed by 22 November 2026. Eligible trainees then receive the fellowship application; final applications close 18 December 2026.",
        "application_url": "https://www.internetsociety.org/fellowship/",
    },
    {
        "title": "Dalai Lama Fellows 2027",
        "provider": "Dalai Lama Fellows",
        "summary": "A year-long contemplative leadership program for changemakers developing social-impact projects in their communities.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Leadership curriculum, coaching and a global fellows community",
        "deadline": deadline(2026, 11, 11, 22, 0),
        "country": "Global",
        "location_label": "Global · Primarily virtual",
        "is_remote": True,
        "eligible_countries": ["Worldwide"],
        "education_levels": ["university", "masters", "phd", "other"],
        "fields_of_study": ["Social Sciences", "Education", "Public Policy", "Business", "Health", "Environment"],
        "employment_statuses": ["student", "employed", "unemployed", "self_employed", "freelancer"],
        "eligibility_notes": "Applicants must be actively engaged in a social-change project or present a concrete, feasible plan and remain committed to it throughout the fellowship year.",
        "application_url": "https://dalailamafellows.com/apply/",
    },
    {
        "title": "ECDC Fellowship Programme — EPIET and EUPHEM 2027",
        "provider": "European Centre for Disease Prevention and Control",
        "summary": "A two-year applied fellowship with field epidemiology and public-health microbiology pathways at training sites across Europe.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Two-year applied training placement",
        "deadline": deadline(2026, 10, 26, 23, 0),
        "country": "European Union",
        "location_label": "EU/EEA training sites",
        "eligible_countries": EU_EEA_COUNTRIES,
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["Public Health", "Epidemiology", "Medicine", "Veterinary Medicine", "Microbiology", "Biology", "Bioinformatics", "Nursing"],
        "employment_statuses": ["employed", "unemployed"],
        "eligibility_notes": "Applicants must be EU/EEA nationals and know at least two EU/EEA official languages, including English at B2 or above. A relevant master's plus experience is required; the microbiology path also accepts a relevant PhD under its detailed rules.",
        "application_url": "https://www.ecdc.europa.eu/en/about-us/work-ecdc/call-application-ecdc-fellowship-programme-epiet-and-euphem-paths-eu-track",
    },
    {
        "title": "Career Development Fellowship 2027",
        "provider": "The Royal Society",
        "summary": "A four-year postdoctoral fellowship helping early-career researchers from underrepresented Black heritage backgrounds establish independent research careers in UK STEM.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Up to £703,800 over four years plus training and mentoring",
        "deadline": deadline(2026, 11, 18),
        "country": "United Kingdom",
        "location_label": "United Kingdom",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["phd"],
        "fields_of_study": ["Biological Sciences", "Biomedical Sciences", "Chemistry", "Engineering", "Mathematics", "Physics"],
        "employment_statuses": ["employed", "unemployed"],
        "eligibility_notes": "Applicants must self-identify as Black or mixed Black heritage, have a PhD by the funding start date, have under 24 months of postdoctoral experience, meet the UK education or research connection rule, and conduct eligible natural-sciences research in the UK.",
        "application_url": "https://www.royalsociety.org/grants/career-development-fellowship/",
    },
    {
        "title": "Absa Youth Entrepreneurship Fund 2026",
        "provider": "Absa Group and Tshiamo Foundation",
        "summary": "Grant funding and hands-on business support for young South African entrepreneurs taking an early-stage venture from a working idea toward a sustainable business.",
        "category": Opportunity.Category.FUNDING,
        "benefit": "Grant funding, mentorship, market access and business support",
        "deadline": deadline(2026, 10, 31),
        "country": "South Africa",
        "location_label": "South Africa",
        "eligible_countries": ["South Africa"],
        "education_levels": [],
        "fields_of_study": [],
        "employment_statuses": ["self_employed", "unemployed", "employed"],
        "requires_business": True,
        "requires_local_residency": True,
        "eligibility_notes": "For young South African entrepreneurs with an early-stage business or working idea. Review the provider's FAQ and application form for age, registration, trading-stage, and documentation requirements.",
        "application_url": "https://www.absa.africa/absa-youth-entrepreneurship-fund/",
    },
    {
        "title": "Ibrahim Leadership Fellowship 2027 — AfDB",
        "provider": "Mo Ibrahim Foundation and African Development Bank",
        "summary": "A senior leadership fellowship placing an experienced African professional in the executive office of the African Development Bank in Abidjan.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "US$100,000 stipend for a 12-month placement",
        "deadline": deadline(2026, 11, 20),
        "country": "Côte d’Ivoire",
        "location_label": "Abidjan, Côte d’Ivoire",
        "eligible_countries": AFRICAN_COUNTRIES,
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["Economics", "Public Policy", "Development Studies", "Finance", "Business", "International Relations"],
        "employment_statuses": ["employed", "self_employed"],
        "max_age": 40,
        "eligibility_notes": "For nationals of an African country with a master's degree, at least seven years of relevant experience, leadership ability, and professional English or French. Applicants must normally be under 40; women with children may apply up to age 45.",
        "application_url": "https://mo.ibrahim.foundation/fellowships",
    },
    {
        "title": "Ibrahim Leadership Fellowship 2027 — UNECA",
        "provider": "Mo Ibrahim Foundation and UN Economic Commission for Africa",
        "summary": "A senior leadership fellowship placing an experienced African professional with the UN Economic Commission for Africa in Addis Ababa.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "US$100,000 stipend for a 12-month placement",
        "deadline": deadline(2026, 11, 20),
        "country": "Ethiopia",
        "location_label": "Addis Ababa, Ethiopia",
        "eligible_countries": AFRICAN_COUNTRIES,
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["Economics", "Public Policy", "Development Studies", "Finance", "Business", "International Relations"],
        "employment_statuses": ["employed", "self_employed"],
        "max_age": 40,
        "eligibility_notes": "For nationals of an African country with a master's degree, at least seven years of relevant experience, and a record of leadership. Applicants must normally be under 40; women with children may apply up to age 45. Check the host-specific notice for language requirements.",
        "application_url": "https://mo.ibrahim.foundation/fellowships",
    },
    {
        "title": "Ibrahim Leadership Fellowship 2027 — ITC",
        "provider": "Mo Ibrahim Foundation and International Trade Centre",
        "summary": "A senior leadership fellowship placing an experienced African professional with the International Trade Centre in Geneva.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "US$100,000 stipend for a 12-month placement",
        "deadline": deadline(2026, 11, 20),
        "country": "Switzerland",
        "location_label": "Geneva, Switzerland",
        "eligible_countries": AFRICAN_COUNTRIES,
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["Economics", "International Trade", "Public Policy", "Development Studies", "Finance", "Business"],
        "employment_statuses": ["employed", "self_employed"],
        "max_age": 40,
        "eligibility_notes": "For nationals of an African country with a master's degree, at least seven years of relevant experience, and strong leadership ability. Applicants must normally be under 40; women with children may apply up to age 45. Check the ITC notice for its language requirements.",
        "application_url": "https://mo.ibrahim.foundation/fellowships",
    },
    {
        "title": "Maurice R. Greenberg World Fellows Program 2027",
        "provider": "Yale University",
        "summary": "A four-month residential leadership program for accomplished non-U.S. practitioners making a positive impact in their countries and fields.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Living stipend, furnished housing, medical insurance and round-trip travel",
        "deadline": deadline(2026, 12, 2, 19, 0),
        "country": "United States",
        "location_label": "New Haven, Connecticut",
        "eligible_countries": [],
        "education_levels": [],
        "fields_of_study": [],
        "employment_statuses": ["employed", "self_employed", "unemployed", "freelancer"],
        "eligibility_notes": "Applicants must be citizens of a country other than the United States, be fluent in English, have a strong record of leadership and impact, and commit to full-time residence at Yale from mid-August through mid-December. Full-time students and academics are not eligible.",
        "application_url": "https://jackson.yale.edu/international-leadership-center/yale-world-fellows",
    },
    {
        "title": "Lisa Jardine Grant Scheme 2026",
        "provider": "The Royal Society",
        "summary": "Travel and research grants for early-career scholars using history-of-science collections and building interdisciplinary research connections.",
        "category": Opportunity.Category.GRANT,
        "benefit": "Research travel and subsistence grant",
        "deadline": deadline(2026, 10, 14),
        "country": "United Kingdom",
        "location_label": "Research visits to eligible collections",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["masters", "phd"],
        "fields_of_study": ["History", "History of Science", "Humanities", "Social Sciences", "Science"],
        "employment_statuses": ["student", "employed"],
        "eligibility_notes": "Applicants must be doctoral candidates or hold an early-career post or fellowship at a university or nonprofit host organization. Applications require two academic references and organizational approval before the deadline.",
        "application_url": "https://www.royalsociety.org/grants/lisa-jardine/",
    },
    {
        "title": "Dorothy Hodgkin Fellowship 2027",
        "provider": "The Royal Society",
        "summary": "A flexible early-career research fellowship for outstanding scientists who need adaptable working arrangements because of personal circumstances.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Independent research funding, salary contribution and flexible support",
        "deadline": deadline(2026, 10, 29),
        "country": "United Kingdom",
        "location_label": "United Kingdom",
        "eligible_countries": ["Worldwide"],
        "education_levels": ["phd"],
        "fields_of_study": ["Biological Sciences", "Biomedical Sciences", "Chemistry", "Engineering", "Mathematics", "Physics"],
        "employment_statuses": ["employed", "unemployed"],
        "eligibility_notes": "For early-career researchers in the Royal Society's natural-sciences remit who have a strong scientific track record and require a flexible working pattern due to personal circumstances. The fellowship must be held at an eligible UK organization.",
        "application_url": "https://www.royalsociety.org/grants/dorothy-hodgkin-fellowship/",
    },
    {
        "title": "Civic Leaders Fellowship 2027",
        "provider": "Ronald Reagan Presidential Foundation and Institute",
        "summary": "A semester-long leadership and professional-development program helping undergraduate students grow their civic knowledge, professional skills, and networks.",
        "category": Opportunity.Category.FELLOWSHIP,
        "benefit": "Hybrid leadership program and professional development",
        "deadline": deadline(2026, 10, 31),
        "country": "United States",
        "location_label": "Hybrid · California and Washington, DC",
        "is_remote": True,
        "requires_physical_presence": True,
        "eligible_countries": ["United States"],
        "education_levels": ["university"],
        "fields_of_study": [],
        "employment_statuses": ["student"],
        "eligibility_notes": "Designed for current undergraduate students able to participate in the January–May 2027 hybrid and place-based program. Review the official application for institution, location, and attendance requirements.",
        "application_url": "https://www.reaganfoundation.org/reagan-institute/centers/civics-education-opportunity/program/civic-leaders-fellowship",
    },
]


class Command(BaseCommand):
    help = "Create or update a curated set of currently open, provider-verified opportunities."

    def add_arguments(self, parser):
        parser.add_argument(
            "--replace-demo",
            action="store_true",
            help="Unpublish the example.com demo opportunities after the real listings are seeded.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        created = 0
        updated = 0

        for row in ROWS:
            defaults = {
                **row,
                "application_mode": Opportunity.ApplicationMode.EXTERNAL,
                "requires_physical_presence": row.get(
                    "requires_physical_presence",
                    not row.get("is_remote", False) and row.get("country") not in {"", "Global"},
                ),
                "requires_local_residency": row.get("requires_local_residency", False),
                "is_published": True,
                "review_status": Opportunity.ReviewStatus.APPROVED,
                "source_url": row["application_url"],
                "share_note": "Verified against the official provider page on 9 October 2026.",
            }
            opportunity, was_created = Opportunity.objects.update_or_create(
                title=row["title"], provider=row["provider"], defaults=defaults
            )
            created += int(was_created)
            updated += int(not was_created)
            self.stdout.write(f"{'Created' if was_created else 'Updated'}: {opportunity.title}")

        unpublished = 0
        if options["replace_demo"]:
            unpublished = Opportunity.objects.filter(
                application_url__startswith="https://example.com/getneba-demo/",
                is_published=True,
            ).update(is_published=False)

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} real opportunities ({updated} updated); "
                f"unpublished {unpublished} demo opportunities."
            )
        )
