# Generated by Django 5.2.5 on 2026-09-27 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('errands', 'Errands'), ('moving', 'Moving & assembly'), ('events', 'Event help'), ('tutoring', 'Tutoring'), ('tech', 'Tech help'), ('other', 'Other')], default='other', max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_note', models.CharField(blank=True, max_length=160)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
