# Generated by Django 5.2.5 on 2026-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_private_task_requested_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='involves_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='item_already_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(blank=True, choices=[('documents', 'Documents'), ('food', 'Food or groceries'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='moderation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('held', 'Needs review'), ('rejected', 'Rejected')], default='approved', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='policy_version',
            field=models.CharField(default='mvp-v1', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=12),
        ),
    ]
