# Generated by Django 5.2.5 on 2026-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_nearby_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='helpers_needed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
