# Generated by Django 5.2.5 on 2026-10-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_safetyreport_task_delete_review'),
        ('bookings', '0008_remove_applicationmessage_application_and_more'),
        ('tasks', '0008_task_helpers_needed_task_is_recurring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
