// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[info]" | "/activity" | "/alerts" | "/applications" | "/applications/[id]" | "/assistant" | "/assistant/interview" | "/billing" | "/credits" | "/dashboard" | "/forgot-password" | "/install" | "/local-help" | "/login" | "/matches" | "/members/[id]" | "/messages" | "/messages/[id]" | "/my-opportunities" | "/my-opportunities/[id]" | "/my-opportunities/new" | "/notifications" | "/offers" | "/offers/[id]" | "/offers/new" | "/onboarding" | "/operations" | "/operations/[section]" | "/opportunities" | "/opportunities/[id]" | "/opportunities/fellowships" | "/opportunities/grants" | "/opportunities/internships" | "/opportunities/jobs" | "/opportunities/scholarships" | "/opportunities/startup" | "/opportunity-applications/[id]" | "/opportunity-applications/[id]/messages" | "/opportunity-check" | "/organization/analytics" | "/organization/applicants" | "/organization/assistant" | "/organization/dashboard" | "/organization/onboarding" | "/organization/opportunities" | "/organization/opportunities/[id]" | "/organization/opportunities/new" | "/pricing" | "/profile" | "/register" | "/reset-password" | "/safety" | "/saved" | "/settings" | "/stories" | "/tasks" | "/tasks/[id]" | "/tasks/mine" | "/tasks/new" | "/u/[id]" | "/verify" | "/verify-email"
type PageRoutes = never
type LayoutRoutes = "/" | "/opportunities/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[info]": { "info": string; }
  "/activity": {}
  "/alerts": {}
  "/applications": {}
  "/applications/[id]": { "id": string; }
  "/assistant": {}
  "/assistant/interview": {}
  "/billing": {}
  "/credits": {}
  "/dashboard": {}
  "/forgot-password": {}
  "/install": {}
  "/local-help": {}
  "/login": {}
  "/matches": {}
  "/members/[id]": { "id": string; }
  "/messages": {}
  "/messages/[id]": { "id": string; }
  "/my-opportunities": {}
  "/my-opportunities/[id]": { "id": string; }
  "/my-opportunities/new": {}
  "/notifications": {}
  "/offers": {}
  "/offers/[id]": { "id": string; }
  "/offers/new": {}
  "/onboarding": {}
  "/operations": {}
  "/operations/[section]": { "section": string; }
  "/opportunities": {}
  "/opportunities/[id]": { "id": string; }
  "/opportunities/fellowships": {}
  "/opportunities/grants": {}
  "/opportunities/internships": {}
  "/opportunities/jobs": {}
  "/opportunities/scholarships": {}
  "/opportunities/startup": {}
  "/opportunity-applications/[id]": { "id": string; }
  "/opportunity-applications/[id]/messages": { "id": string; }
  "/opportunity-check": {}
  "/organization/analytics": {}
  "/organization/applicants": {}
  "/organization/assistant": {}
  "/organization/dashboard": {}
  "/organization/onboarding": {}
  "/organization/opportunities": {}
  "/organization/opportunities/[id]": { "id": string; }
  "/organization/opportunities/new": {}
  "/pricing": {}
  "/profile": {}
  "/register": {}
  "/reset-password": {}
  "/safety": {}
  "/saved": {}
  "/settings": {}
  "/stories": {}
  "/tasks": {}
  "/tasks/[id]": { "id": string; }
  "/tasks/mine": {}
  "/tasks/new": {}
  "/u/[id]": { "id": string; }
  "/verify": {}
  "/verify-email": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/opportunities/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
