"use client";

import { FormEvent, RefObject, useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, Link2, LoaderCircle, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { api } from "@/lib/api";

const groups = [
  ["work", "Work", [["job", "Job"], ["internship", "Internship"], ["freelance", "Freelance project"], ["contract", "Contract"], ["paid-task", "Paid task"]]],
  ["learn", "Learn", [["scholarship", "Scholarship"], ["fellowship", "Fellowship"], ["training", "Training"], ["mentorship", "Mentorship"]]],
  ["build", "Build", [["cofounder", "Co-founder"], ["collaboration", "Collaboration"], ["project", "Project"], ["competition", "Competition"], ["accelerator", "Accelerator"]]],
  ["fund", "Fund", [["grant", "Grant"], ["funding", "Funding"], ["sponsorship", "Sponsorship"]]],
] as const;
const backendCategory: Record<string, string> = { job: "job", internship: "internship", freelance: "job", contract: "job", "paid-task": "job", scholarship: "scholarship", fellowship: "fellowship", training: "training", mentorship: "training", cofounder: "startup", collaboration: "startup", project: "startup", competition: "competition", accelerator: "startup", grant: "grant", funding: "funding", sponsorship: "funding", other: "tender" };
const benefitCopy: Record<string, string> = { cofounder: "What are you offering?", job: "Salary or compensation", internship: "Stipend or support", scholarship: "What the scholarship covers", fellowship: "Stipend, access, or support", training: "Fee, scholarship, or support", grant: "Funding amount or range", funding: "Funding amount or terms", competition: "Prize or recognition", accelerator: "Funding, access, or support", default: "What will someone get?" };
function typeLabel(type: string) { for (const group of groups) { const match = group[2].find((option) => option[0] === type); if (match) return match[1]; } return "Opportunity"; }
const listValue = (value: FormDataEntryValue | null) => String(value || "").split(",").map((item) => item.trim()).filter(Boolean);

export default function NewOrganizationOpportunityPage() {
const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams(); const editId = searchParams.get("edit"); const personal = pathname.startsWith("/my-opportunities"); const base = personal ? "/my-opportunities" : "/organization"; const formRef = useRef<HTMLFormElement>(null);
const [type, setType] = useState("job"); const [category, setCategory] = useState("work"); const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [importBusy, setImportBusy] = useState(false); const [contentBusy, setContentBusy] = useState(false); const [error, setError] = useState(""); const [importError, setImportError] = useState(""); const [sourceLink, setSourceLink] = useState(""); const [sourceContent, setSourceContent] = useState(""); const [imported, setImported] = useState(false);
  const activeTypes = groups.find(([value]) => value === category)?.[2] || groups[0][2];
  const currentBenefit = benefitCopy[type] || benefitCopy[backendCategory[type]] || benefitCopy.default;

  function changeCategory(value: string) { setCategory(value); const first = groups.find(([group]) => group === value)?.[2][0][0] || "job"; setType(first); }
  function applyStructuredFields(fields: Record<string, unknown>) { const mappedType = Object.keys(backendCategory).find((key) => backendCategory[key] === fields.category) || "job"; setType(mappedType); setCategory(groups.find(([_, __, options]) => options.some(([value]) => value === mappedType))?.[0] || "work"); window.setTimeout(() => { const form = formRef.current; if (!form) return; const setValue = (name: string, value: unknown) => { const input = form.elements.namedItem(name) as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null; if (input && value !== null && value !== undefined && value !== "") input.value = Array.isArray(value) ? value.join(", ") : String(value); }; ["title", "provider", "summary", "share_note", "location_label", "country", "benefit", "deadline", "application_mode", "application_url", "source_url", "eligible_countries", "education_levels", "fields_of_study", "employment_statuses", "eligibility_notes"].forEach((name) => setValue(name, fields[name])); const remote = form.elements.namedItem("is_remote") as HTMLInputElement | null; if (remote) remote.checked = Boolean(fields.is_remote); const business = form.elements.namedItem("requires_business") as HTMLInputElement | null; if (business) business.checked = Boolean(fields.requires_business); setImported(true); }, 0); }
  async function importFromLink() { if (!sourceLink.trim()) { setImportError("Paste the exact opportunity link first."); return; } setImportBusy(true); setImportError(""); try { const data = await api<{ fields: Record<string, unknown> }>(`${personal ? "/my-opportunities" : "/organization/opportunities"}/fetch-link/`, { method: "POST", body: JSON.stringify({ url: sourceLink.trim() }) }); const fields = data.fields; const mappedType = Object.keys(backendCategory).find((key) => backendCategory[key] === fields.category) || "job"; setType(mappedType); setCategory(groups.find(([_, __, options]) => options.some(([value]) => value === mappedType))?.[0] || "work"); window.setTimeout(() => { const form = formRef.current; if (!form) return; const setValue = (name: string, value: unknown) => { const input = form.elements.namedItem(name) as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null; if (input && value !== null && value !== undefined && value !== "") input.value = Array.isArray(value) ? value.join(", ") : String(value); }; ["title", "summary", "location_label", "benefit", "deadline", "application_url", "source_url", "eligible_countries", "education_levels", "fields_of_study", "employment_statuses"].forEach((name) => setValue(name, fields[name])); setValue("eligibility_notes", fields.eligibility_notes); const remote = form.elements.namedItem("is_remote") as HTMLInputElement | null; if (remote) remote.checked = Boolean(fields.is_remote); setImported(true); }, 0); } catch (exception) { setImportError((exception as Error).message); } finally { setImportBusy(false); } }
  function field(name: string) { const input = formRef.current?.elements.namedItem(name) as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null; return input?.value || ""; }
  async function importFromContent() { if (!sourceContent.trim()) { setImportError("Paste the opportunity content first."); return; } setContentBusy(true); setImportError(""); try { const data = await api<{ fields: Record<string, unknown> }>(`${personal ? "/my-opportunities" : "/organization/opportunities"}/fetch-link/`, { method: "POST", body: JSON.stringify({ content: sourceContent.trim() }) }); applyStructuredFields(data.fields); } catch (exception) { setImportError((exception as Error).message); } finally { setContentBusy(false); } }
  useEffect(() => { if (!personal || !editId) return; api<Record<string, unknown>>(`/my-opportunities/${editId}/`).then((data) => applyStructuredFields(data)).catch((exception) => setError((exception as Error).message)); }, [personal, editId]);
  function startReview(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); if (!field("title").trim() || !field("summary").trim()) { setError("Add a title and short description before reviewing your opportunity."); return; } if (personal && !field("provider").trim()) { setError("Add the organisation offering this opportunity."); return; } if (field("application_mode") !== "internal" && !field("application_url").trim()) { setError("Add the provider's official application link."); return; } setReview(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function publish() { setBusy(true); setError(""); const form = new FormData(formRef.current!); const required = listValue(form.get("required_requirements")); const nice = listValue(form.get("nice_to_have")); const documents = listValue(form.get("documents")); const payload = { title: form.get("title"), provider: form.get("provider"), summary: form.get("summary"), share_note: form.get("share_note"), category: backendCategory[type], application_mode: personal ? "external" : form.get("application_mode"), application_url: form.get("application_url"), deadline: form.get("deadline") || null, country: form.get("country") || "", location_label: form.get("location_label"), is_remote: form.get("is_remote") === "true", benefit: form.get("benefit"), eligibility_notes: [form.get("eligibility_notes"), required.length ? `Required: ${required.join(", ")}` : "", nice.length ? `Nice to have: ${nice.join(", ")}` : "", documents.length ? `Documents: ${documents.join(", ")}` : ""].filter(Boolean).join("\n"), eligible_countries: listValue(form.get("eligible_countries")), education_levels: listValue(form.get("education_levels")), fields_of_study: listValue(form.get("fields_of_study")), employment_statuses: listValue(form.get("employment_statuses")), min_age: null, max_age: null, requires_business: form.get("requires_business") === "true", source_url: form.get("source_url") || form.get("application_url") }; const endpoint = personal && editId ? "/my-opportunities/" + editId + "/" : personal ? "/my-opportunities/" : "/organization/opportunities/"; const method = personal && editId ? "PATCH" : "POST"; try { await api(endpoint, { method, body: JSON.stringify(payload) }); router.push(personal ? "/my-opportunities" : "/organization/dashboard"); } catch (exception) { setError((exception as Error).message); setBusy(false); } }

  return <main className="organization-flow post-opportunity-flow container"><div className="post-opportunity-rail"><Link className="back-link" href={personal ? base : `${base}/dashboard`}><ArrowLeft size={15} /> {personal ? "My opportunities" : "Organization dashboard"}</Link><span className="eyebrow">POST AN OPPORTUNITY</span><div className="post-progress"><span className={!review ? "active" : ""}>Details</span><i /><span className={review ? "active" : ""}>Review</span><i /><span>Publish</span></div><p>Easy to create, structured underneath — so the right people can find it.</p></div>
    <section className="organization-form-card post-opportunity-card"><div className="organization-form-heading"><span className="organization-icon"><FileText size={22} /></span><span className="landing-eyebrow"><ShieldCheck size={14} /> PUBLISH WITH TRUST</span><h1>{review ? "Review your opportunity." : editId ? "Edit your opportunity." : "Post an opportunity."}</h1><p>{review ? "Check how your opportunity will be understood before you send it for review." : editId ? "Update your submission and send it back for review. Published opportunities are locked." : "Share something worth pursuing. We’ll collect the details that help the right people find it."}</p></div>
      {!review && <><div className="post-form-overview"><span className="active"><b>1</b> Type</span><i /><span><b>2</b> Details</span><i /><span><b>3</b> Audience</span><i /><span><b>4</b> Review</span></div><section className="link-import-panel"><div className="link-import-copy"><span className="link-import-icon"><Sparkles size={17} /></span><div><strong>Already have a page?</strong><p>Paste a link and we’ll bring the details into the form for you to check.</p></div></div><div className="link-import-controls"><div className="link-input-wrap"><Link2 size={16} /><input aria-label="Opportunity page link" type="url" value={sourceLink} onChange={(event) => setSourceLink(event.target.value)} placeholder="https://example.org/opportunity" /></div><button type="button" className="button button-dark compact" onClick={() => void importFromLink()} disabled={importBusy}>{importBusy ? <><LoaderCircle size={15} /> Reading page…</> : "Fill form"}</button></div><div className="content-import-controls"><textarea aria-label="Paste opportunity content" value={sourceContent} onChange={(event) => setSourceContent(event.target.value)} placeholder="Or paste the full announcement here — role, deadline, pay, eligibility, and application details…" /><button type="button" className="button button-outline compact" onClick={() => void importFromContent()} disabled={contentBusy}>{contentBusy ? <><LoaderCircle size={15} /> Structuring content…</> : <><Sparkles size={15} /> Structure pasted content</>}</button></div>{importError && <p className="link-import-error" role="alert">{importError}</p>}{imported && <p className="link-import-success"><CheckCircle2 size={15} /> Details added. Review and correct anything that needs changing.</p>}</section></>}
      {review && <Review formRef={formRef} type={type} onEdit={() => setReview(false)} onPublish={() => void publish()} busy={busy} error={error} />}<form ref={formRef} className={`organization-form dynamic-opportunity-form${imported ? " imported-form" : ""}${review ? " post-form-hidden" : ""}`} onSubmit={startReview}>
        <section className="post-form-section"><span className="post-section-number">01</span><div><span className="eyebrow">START WITH THE TYPE</span><h2>What kind of opportunity are you sharing?</h2><p>Select the type and we’ll keep the rest of the form relevant.</p></div><div className="post-category-grid">{groups.map(([value, label]) => <button type="button" key={value} className={category === value ? "active" : ""} onClick={() => changeCategory(value)}>{label}</button>)}</div><div className="post-type-grid">{activeTypes.map(([value, label]) => <button type="button" key={value} className={type === value ? "active" : ""} onClick={() => setType(value)}><span>{type === value && <Check size={14} />}</span>{label}</button>)}</div></section>
        <section className="post-form-section"><span className="post-section-number">02</span><div><span className="eyebrow">BASIC INFORMATION</span><h2>Tell people about it.</h2></div>{personal && <label><span>Offered by</span><input name="provider" required maxLength={180} placeholder="Organisation or programme name" /></label>}<label><span>Title</span><input name="title" required maxLength={220} placeholder={type === "cofounder" ? "e.g. Technical Co-founder Wanted" : `e.g. ${typeLabel(type)}`} /></label><label><span>Short description</span><textarea name="summary" required maxLength={1800} placeholder="What is this opportunity about?" /></label>{personal && <label><span>Why are you sharing this? <small>Optional</small></span><textarea name="share_note" maxLength={500} placeholder="Who could this help, or what made it worth passing on?" /></label>}<div className="form-row"><label><span>Location <small>Optional</small></span><input name="location_label" placeholder="City, country, region, or worldwide" /></label><label><span>Country <small>Optional</small></span><input name="country" placeholder="Country or worldwide" /></label></div><label className="organization-check"><input name="is_remote" type="checkbox" value="true" /><span>Remote opportunity</span></label></section>
        <section className="post-form-section"><span className="post-section-number">03</span><div><span className="eyebrow">WHAT IT OFFERS</span><h2>Make the value clear.</h2><p>People should understand what they’ll get by pursuing this.</p></div><label><span>{currentBenefit}</span><input name="benefit" maxLength={220} placeholder={currentBenefit} /></label></section>
        <section className="post-form-section"><span className="post-section-number">04</span><div><span className="eyebrow">WHO IT’S FOR</span><h2>Help the right people recognize themselves.</h2></div><div className="form-row"><label><span>Eligible locations <small>Optional</small></span><input name="eligible_countries" placeholder="Nigeria, Africa, Worldwide" /></label><label><span>Experience or audience <small>Optional</small></span><input name="employment_statuses" placeholder="Student, Founder, Entry level" /></label></div><div className="form-row"><label><span>Education <small>Optional</small></span><input name="education_levels" placeholder="Any, Bachelor's, Master's" /></label><label><span>Skills or fields <small>Optional</small></span><input name="fields_of_study" placeholder="Python, Marketing, Design" /></label></div><label className="organization-check"><input name="requires_business" type="checkbox" value="true" /><span>Applicants need an active business or idea</span></label></section>
        <section className="post-form-section"><span className="post-section-number">05</span><div><span className="eyebrow">REQUIREMENTS</span><h2>What does someone need to pursue it?</h2></div><label><span>Required <small>Optional, comma-separated</small></span><input name="required_requirements" placeholder="Skills, qualifications, experience" /></label><label><span>Nice to have <small>Optional, comma-separated</small></span><input name="nice_to_have" placeholder="Things that strengthen an application" /></label><label><span>Documents required <small>Optional, comma-separated</small></span><input name="documents" placeholder="CV, portfolio, transcript" /></label></section>
        <section className="post-form-section"><span className="post-section-number">06</span><div><span className="eyebrow">DEADLINE AND NEXT STEP</span><h2>How should people pursue it?</h2></div><div className="form-row"><label><span>Deadline <small>Optional</small></span><input name="deadline" type="datetime-local" /></label>{personal ? <label><span>Application method</span><input name="application_mode" value="external" readOnly /><small>Community shares always send people to the provider&apos;s official application.</small></label> : <label><span>Application method</span><select name="application_mode" defaultValue="external"><option value="external">External website</option><option value="internal">Inside Getneba</option></select></label>}</div><label><span>Official application URL</span><input name="application_url" type="url" required={personal || field("application_mode") !== "internal"} placeholder="https://example.org/apply" /></label><label><span>Supporting link <small>Optional</small></span><input name="source_url" type="url" placeholder="https://example.org/details" /></label></section>
        {error && <p className="error-box" role="alert">{error}</p>}<div className="post-form-footer"><span><ShieldCheck size={14} /> You’ll review everything before it is submitted.</span><button className="button button-dark post-review-button">Review opportunity <ArrowRight size={17} /></button></div>
      </form>
    </section></main>;
}

function Review({ formRef, type, onEdit, onPublish, busy, error }: { formRef: RefObject<HTMLFormElement | null>; type: string; onEdit: () => void; onPublish: () => void; busy: boolean; error: string }) {
  const form = formRef.current; const value = (name: string) => (form?.elements.namedItem(name) as HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement | null)?.value || "Not supplied"; const checks = [{ label: "Title is clear", done: value("title") !== "Not supplied" }, { label: "Opportunity type identified", done: Boolean(type) }, { label: "Who it’s for is defined", done: value("eligible_countries") !== "Not supplied" || value("employment_statuses") !== "Not supplied" }, { label: "Application instructions added", done: value("application_url") !== "Not supplied" || value("application_mode") === "internal" }];
  return <div className="post-review"><div className="post-review-notice"><Sparkles size={19} /><div><strong>Your opportunity is ready to review.</strong><p>We found {checks.filter((check) => !check.done).length} thing{checks.filter((check) => !check.done).length === 1 ? "" : "s"} you may want to add before publishing.</p></div></div><div className="post-review-checks">{checks.map((check) => <span className={check.done ? "done" : "needs"} key={check.label}>{check.done ? <Check size={14} /> : <span>!</span>}{check.label}</span>)}</div><article className="post-preview-card"><span className="opportunity-type">{typeLabel(type)}</span><h2>{value("title")}</h2><p className="opportunity-provider">{value("location_label")} · {value("country")}</p><p>{value("summary")}</p><div><span>{value("benefit")}</span><span>{value("deadline") === "Not supplied" ? "No deadline" : `Closes ${value("deadline")}`}</span></div></article>{error && <p className="error-box" role="alert">{error}</p>}<div className="post-review-actions"><button className="button button-outline" onClick={onEdit}>← Edit</button><button className="button button-dark" onClick={onPublish} disabled={busy}>{busy ? "Submitting…" : "Submit for review"}<ArrowRight size={17} /></button></div></div>;
}
