"use client";

import Link from "next/link";
import { useParams, usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, Check, ChevronRight, Edit3, Eye, Link2, MessageCircle, Share2, UsersRound } from "lucide-react";
import { api } from "@/lib/api";

type Applicant = { id: number; application_id: string; name: string; country: string; status: string; match_score: number; match_reasons: string[]; missing: string[] };
type Workspace = { opportunity: { title: string; category: string; review_status: string; is_published: boolean; deadline: string | null; summary: string; benefit?: string; location_label?: string; is_remote?: boolean }; metrics: { matches: number; applications: number; qualified: number; shortlisted: number; views: number; application_rate: number }; applicants: Applicant[]; audience: { total_matches: number; high_confidence: number; countries: { label: string; count: number }[] } };
type Tab = "overview" | "interested" | "analytics";
const statusLabels: Record<string, string> = { preparing: "Interested", applied: "Interested", shortlisted: "Shortlisted", interview: "Contacted", awarded: "Accepted", unsuccessful: "Rejected" };

export default function OrganizationOpportunityWorkspace() {
  const { id } = useParams<{ id: string }>();
  const pathname = usePathname();
  const base = pathname.startsWith("/my-opportunities") ? "/my-opportunities" : "/organization/opportunities";
  const [workspace, setWorkspace] = useState<Workspace | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [error, setError] = useState("");
  useEffect(() => { api<Workspace>(`${base}/${id}/workspace/`).then(setWorkspace).catch((err) => setError(err.message)); }, [base, id]);
  if (error) return <main className="organization-workspace container"><p className="error-box">{error}</p><Link className="text-link" href={base}>Back to my opportunities</Link></main>;
  if (!workspace) return <main className="organization-workspace container"><p role="status">Loading opportunity workspace...</p></main>;
  const { opportunity, metrics, applicants, audience } = workspace;
  const views = metrics.views;
  return <main className="opportunity-workspace-v1 container">
    <Link className="back-link" href={base}><ArrowLeft size={15} /> My opportunities</Link>
    <header className="opportunity-workspace-header"><div><div className="workspace-title-row"><span className={`my-opportunity-status ${opportunity.is_published ? "active" : "closed"}`}><i />{opportunity.is_published ? "Active" : "Draft"}</span><span className="eyebrow">OPPORTUNITY WORKSPACE</span></div><h1>{opportunity.title}</h1><p>{opportunity.category} · {opportunity.is_remote ? "Remote" : opportunity.location_label || "Open location"}{opportunity.deadline ? ` · Closes ${new Date(opportunity.deadline).toLocaleDateString("en-NG", { month: "short", day: "numeric" })}` : ""}</p></div><div className="workspace-header-actions"><button className="button button-outline compact"><Edit3 size={14} /> Edit</button><button className="button button-outline compact"><Share2 size={14} /> Share</button><button className="icon-button" aria-label="More actions"><ChevronRight size={18} /></button></div></header>
    <div className="workspace-metrics workspace-metrics-v1"><div><strong>{views}</strong><span>Views</span></div><div><strong>{metrics.applications}</strong><span>Interested</span></div><div><strong>{metrics.application_rate}%</strong><span>Interest rate</span></div></div>
    <nav className="workspace-tabs" aria-label="Opportunity workspace sections">{([['overview', 'Overview'], ['interested', 'Interested'], ['analytics', 'Analytics']] as [Tab, string][]).map(([value, label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}{value === "interested" && metrics.applications > 0 ? <span className="workspace-tab-count">{metrics.applications}</span> : null}</button>)}</nav>
    {tab === "overview" && <div className="workspace-overview-v1"><section className="workspace-opportunity-copy"><span className="eyebrow">THE OPPORTUNITY</span><h2>{opportunity.title}</h2><p>{opportunity.summary || "Tell people what you are building and who would make it stronger."}</p><h3>What I&apos;m looking for</h3><div className="workspace-chip-list"><span>Relevant experience</span><span>Strong communication</span><span>Growth mindset</span></div><h3>What I&apos;m offering</h3><div className="workspace-offering"><span>{opportunity.benefit || "A meaningful opportunity to build together"}</span><span>{opportunity.is_remote ? "Remote" : opportunity.location_label || "Flexible location"}</span></div></section><aside className="workspace-performance-card"><div className="workspace-card-icon"><BarChart3 size={18} /></div><span className="eyebrow">OPPORTUNITY PERFORMANCE</span><div className="workspace-performance-number"><strong>{views}</strong><span>Views</span></div><div className="workspace-performance-number"><strong>{metrics.applications}</strong><span>Interested</span></div><div className="workspace-performance-rate"><strong>{metrics.application_rate}%</strong><span>Interest rate</span></div><button className="button button-outline compact" onClick={() => setTab("analytics")}>View analytics <ChevronRight size={14} /></button></aside></div>}
    {tab === "interested" && <section className="workspace-section workspace-interested-v1"><div className="workspace-section-heading"><div><span className="eyebrow">PEOPLE WHO APPLIED</span><h2>{metrics.applications} people applied</h2><p>Review submitted applications, then message people directly in Getneba.</p></div><UsersRound size={24} /></div>{applicants.length ? <div className="workspace-applicant-list">{applicants.map((applicant) => <article className="workspace-applicant-row" key={applicant.id}><span className="workspace-applicant-score">{applicant.match_score}%</span><div><strong>{applicant.name}</strong><small>{applicant.country || "Location not specified"} · {statusLabels[applicant.status] || applicant.status}</small><p>{applicant.match_reasons.join(" · ") || applicant.missing.join(" · ") || "Relevant profile context"}</p></div><div className="workspace-applicant-actions"><Link className="button button-outline compact" href={`/opportunity-applications/${applicant.application_id}`}>Review application</Link><Link className="button button-dark compact" href={`/opportunity-applications/${applicant.application_id}`}><MessageCircle size={14} /> Message</Link></div><Check size={16} className={applicant.match_score >= 75 ? "qualified-mark" : "muted-mark"} /></article>)}</div> : <div className="organization-empty"><UsersRound size={22} /><p>No submitted applications yet.</p></div>}</section>}
    {tab === "analytics" && <section className="workspace-section workspace-analytics-v1"><div className="workspace-section-heading"><div><span className="eyebrow">A SIMPLE READ ON PERFORMANCE</span><h2>What&apos;s helping people find this?</h2><p>Keep an eye on the signals that matter while this opportunity is live.</p></div><BarChart3 size={24} /></div><div className="analytics-highlight-grid"><div><Eye size={16} /><strong>{views}</strong><span>Total views</span></div><div><UsersRound size={16} /><strong>{metrics.applications}</strong><span>Interested</span></div><div><Link2 size={16} /><strong>{metrics.application_rate}%</strong><span>Interest rate</span></div></div><div className="workspace-source-list"><h3>Where people came from</h3>{(audience.countries.length ? audience.countries.slice(0, 4) : [{ label: "Getneba Discover", count: views }]).map((source, index) => <div key={source.label}><span>{index === 0 ? "Getneba Discover" : source.label}</span><strong>{source.count}</strong></div>)}</div></section>}
  </main>;
}
