"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Bell, ChevronRight, CircleHelp, CreditCard, ExternalLink, Globe2, LockKeyhole, LogOut, Mail, Shield, UserRound, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { api, clearToken, getToken } from "@/lib/api";
import { User } from "@/lib/types";
import { PushNotificationSettings } from "@/components/push-notifications";

type Section = "account" | "notifications" | "preferences" | "privacy" | "billing" | "connections" | "help";
const nav: Array<{ id: Section; label: string; icon: typeof UserRound }> = [{ id: "account", label: "Account", icon: UserRound }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "preferences", label: "Opportunity Preferences", icon: Globe2 }, { id: "privacy", label: "Privacy & Security", icon: LockKeyhole }, { id: "billing", label: "Billing", icon: CreditCard }, { id: "connections", label: "Connected Accounts", icon: UsersRound }, { id: "help", label: "Help & Support", icon: CircleHelp }];
const interestOptions = [{ value: "job", label: "Jobs" }, { value: "internship", label: "Internships" }, { value: "scholarship", label: "Scholarships" }, { value: "grant", label: "Grants" }, { value: "fellowship", label: "Fellowships" }, { value: "training", label: "Training" }, { value: "startup", label: "Startup Programs" }, { value: "tender", label: "Tenders & Procurement" }, { value: "competition", label: "Competitions" }, { value: "funding", label: "Business Funding" }, { value: "remote", label: "Remote Opportunities" }];

function SettingRow({ title, detail, children }: { title: string; detail?: string; children?: React.ReactNode }) {
  return <div className="setting-row"><div><strong>{title}</strong>{detail && <p>{detail}</p>}</div>{children}</div>;
}

function AccountSection({ user, onSignOut }: { user: User; onSignOut: () => void }) {
  return <section className="settings-section"><SectionIntro eyebrow="ACCOUNT" title="Account settings" description="Manage the account details and access connected to Getneba." /><div className="settings-card"><SettingRow title="Profile information" detail="Full name, phone number, profile photo and eligibility details"><Link className="settings-link" href="/profile">Edit profile <ChevronRight size={14} /></Link></SettingRow><SettingRow title="Email address" detail={user.email}><a className="settings-link" href={`mailto:${user.email}`}>Contact email <Mail size={14} /></a></SettingRow><SettingRow title="Password" detail="Update your account password"><Link className="settings-link" href="/forgot-password">Change password <ChevronRight size={14} /></Link></SettingRow></div><div className="settings-danger"><div><strong>Delete account</strong><p>Permanently delete your Getneba account and data.</p></div><a className="settings-danger-link" href="mailto:support@getneba.com?subject=Delete%20my%20Getneba%20account">Contact support</a></div><button className="settings-signout" onClick={onSignOut}><LogOut size={15} /> Sign out</button></section>;
}

function SectionIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header className="settings-section-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></header>;
}

function NotificationsSection() {
  const [enabled, setEnabled] = useState({ matches: true, deadlines: true, updates: true, digest: true });
  const toggle = (key: keyof typeof enabled) => setEnabled((current) => ({ ...current, [key]: !current[key] }));
  return <section className="settings-section"><SectionIntro eyebrow="NOTIFICATIONS" title="Notification preferences" description="Choose how Getneba keeps you close to useful opportunities." /><div className="settings-card"><SettingRow title="New opportunities" detail="Notify me when opportunities match my profile"><Switch on={enabled.matches} onClick={() => toggle("matches")} /></SettingRow><SettingRow title="Deadline reminders" detail="7 days before · 3 days before · 24 hours before"><Switch on={enabled.deadlines} onClick={() => toggle("deadlines")} /></SettingRow><SettingRow title="Opportunity updates" detail="Deadline, eligibility, funding, and closure changes"><Switch on={enabled.updates} onClick={() => toggle("updates")} /></SettingRow><SettingRow title="Weekly digest" detail="Every Monday · 8:00 AM"><Switch on={enabled.digest} onClick={() => toggle("digest")} /></SettingRow></div><div className="settings-subsection"><h3>Browser push notifications</h3><PushNotificationSettings /></div></section>;
}

function Switch({ on, onClick }: { on: boolean; onClick: () => void }) {
  return <button className={`settings-switch${on ? " on" : ""}`} onClick={onClick} aria-pressed={on}><i /></button>;
}

function PreferencesSection({ user }: { user: User }) {
  const [selected, setSelected] = useState(user.opportunity_interests || []); const [frequency, setFrequency] = useState("relevant"); const [relocation, setRelocation] = useState(user.relocation_preference || "not_set"); const [destinations, setDestinations] = useState((user.relocation_countries || []).join(", ")); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  function toggle(value: string) { setSelected((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function save() { setBusy(true); setMessage(""); try { await api("/auth/me/", { method: "PATCH", body: JSON.stringify({ opportunity_interests: selected, relocation_preference: relocation, relocation_countries: destinations.split(",").map((value) => value.trim()).filter(Boolean) }) }); setMessage("Preferences saved."); } catch (error) { setMessage((error as Error).message); } finally { setBusy(false); } }
  return <section className="settings-section"><SectionIntro eyebrow="OPPORTUNITY PREFERENCES" title="Shape your radar" description="Tell Getneba what to prioritize. Your profile still holds the detailed eligibility information." /><div className="settings-card"><h3>Opportunity types</h3><div className="settings-choice-grid">{interestOptions.map((option) => <button key={option.value} className={`settings-choice${selected.includes(option.value) ? " selected" : ""}`} onClick={() => toggle(option.value)}><span>{selected.includes(option.value) ? "✓" : ""}</span>{option.label}</button>)}</div><h3>Location and relocation</h3><div className="settings-choice-grid"><button className="settings-choice selected" type="button"><span>✓</span>{user.country || "Current country"}</button><button className={`settings-choice${selected.includes("remote") ? " selected" : ""}`} type="button" onClick={() => toggle("remote")}><span>{selected.includes("remote") ? "✓" : ""}</span>Remote</button></div><label>Would you relocate for an opportunity?<select value={relocation} onChange={(event) => setRelocation(event.target.value as User["relocation_preference"])}><option value="not_set">Not specified yet</option><option value="no">No</option><option value="open">Yes, I am open</option><option value="active">Yes, I am actively looking</option></select></label>{relocation !== "no" && <label>Preferred destination countries <small>Optional</small><input value={destinations} onChange={(event) => setDestinations(event.target.value)} placeholder="United Arab Emirates, Canada, United Kingdom" /><small>Leave blank if you would consider anywhere.</small></label>}<h3>Opportunity frequency</h3><div className="settings-radio-list">{[["high", "Only highly relevant"], ["relevant", "Relevant opportunities"], ["everything", "Show me everything"]].map(([value, label]) => <label key={value}><input type="radio" checked={frequency === value} onChange={() => setFrequency(value)} />{label}</label>)}</div><button className="button button-dark compact" onClick={save} disabled={busy}>{busy ? "Saving..." : "Save preferences"}</button>{message && <p className="settings-feedback" role="status">{message}</p>}</div></section>;
}

function SimpleSection({ section }: { section: Exclude<Section, "account" | "notifications" | "preferences"> }) {
  if (section === "privacy") return <section className="settings-section"><SectionIntro eyebrow="PRIVACY & SECURITY" title="Privacy and security" description="Keep control of how your account and profile are used." /><div className="settings-card"><SettingRow title="Profile visibility" detail="Your profile is currently visible only to you"><span className="settings-status"><Shield size={14} /> Private</span></SettingRow><SettingRow title="Opportunity matching" detail="Allow Getneba to use your profile for personalized matching"><Switch on onClick={() => {}} /></SettingRow><SettingRow title="Personalized recommendations" detail="Use your interests and activity to improve discovery"><Switch on onClick={() => {}} /></SettingRow><SettingRow title="Two-factor authentication" detail="An extra layer of account protection"><button className="settings-link">Not enabled <ChevronRight size={14} /></button></SettingRow><SettingRow title="Active sessions" detail="Chrome · Windows · Last active: now"><button className="settings-link">Manage sessions <ChevronRight size={14} /></button></SettingRow></div><div className="settings-danger"><div><strong>Sign out of all devices</strong><p>End active sessions on other browsers and devices.</p></div><button className="settings-danger-link">Sign out all</button></div></section>;
  if (section === "billing") return <section className="settings-section"><SectionIntro eyebrow="BILLING" title="Getneba account" description="Manage plans and payments when paid intelligence features become available." /><div className="settings-card settings-placeholder"><CreditCard size={22} /><strong>Getneba Free</strong><p>You&apos;re currently using Getneba Free. Billing and subscription management will appear here when available.</p></div></section>;
  if (section === "connections") return <section className="settings-section"><SectionIntro eyebrow="CONNECTED ACCOUNTS" title="Connected accounts" description="Optional integrations that can help Getneba work around your schedule." /><div className="settings-card"><SettingRow title="Google" detail="Use Google for account access"><span className="settings-status">Not connected</span></SettingRow><SettingRow title="WhatsApp" detail="Receive important opportunity alerts"><span className="settings-status muted">Coming later</span></SettingRow><SettingRow title="Calendar" detail="Add application deadlines to your calendar"><span className="settings-status muted">Coming later</span></SettingRow></div></section>;
  return <section className="settings-section"><SectionIntro eyebrow="HELP & SUPPORT" title="Need help?" description="Find answers, report problems, or send feedback to the Getneba team." /><div className="settings-card settings-help-list"><Link href="/help"><CircleHelp size={18} /><span><strong>Help Center</strong><small>Find answers to common questions.</small></span><ChevronRight size={15} /></Link><a href="mailto:support@getneba.com"><Mail size={18} /><span><strong>Contact support</strong><small>Talk to the Getneba team.</small></span><ChevronRight size={15} /></a><Link href="/opportunities"><ExternalLink size={18} /><span><strong>Report an opportunity</strong><small>Flag outdated, suspicious, or incorrect information.</small></span><ChevronRight size={15} /></Link></div><div className="settings-about"><strong>About Getneba</strong><span>Version 1.0.0</span><div><Link href="/terms">Terms of Service</Link><Link href="/privacy">Privacy Policy</Link><Link href="/community-guidelines">Community Guidelines</Link></div></div></section>;
}

export default function SettingsPage() {
  const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [section, setSection] = useState<Section>("account"); const [error, setError] = useState("");
  useEffect(() => { if (!getToken()) { router.replace("/login?next=/settings"); return; } api<User>("/auth/me/").then(setUser).catch((err) => setError(err.message)); }, [router]);
  function signOut() { clearToken(); router.push("/"); }
  if (error) return <main className="settings-page container"><p className="error-box">{error}</p></main>;
  if (!user) return <main className="settings-page container"><p>Loading settings...</p></main>;
  const content = section === "account" ? <AccountSection user={user} onSignOut={signOut} /> : section === "notifications" ? <NotificationsSection /> : section === "preferences" ? <PreferencesSection user={user} /> : <SimpleSection section={section} />;
  return <main className="settings-page container"><header className="settings-page-header"><span className="eyebrow">GETNEBA SETTINGS</span><h1>Settings</h1><p>Manage how your Getneba account and opportunity radar work.</p></header><div className="settings-layout"><nav className="settings-nav" aria-label="Settings sections">{nav.map(({ id, label, icon: Icon }) => <button key={id} className={section === id ? "active" : ""} onClick={() => setSection(id)}><Icon size={17} />{label}</button>)}</nav><div className="settings-content">{content}</div></div></main>;
}
