# Generated by Django 5.2.5 on 2026-10-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_photo_keys'),
        ('tasks', '0009_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
