"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Bell, Bookmark, CalendarClock, Check, ChevronRight, Clock3, ExternalLink, FileText, Flag, HeartHandshake, Sparkles, Target, X } from "lucide-react";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { Opportunity, OpportunityApplication, Page } from "@/lib/types";

const labels: Record<string, string> = { scholarship: "Scholarship", grant: "Grant", job: "Job", internship: "Internship", fellowship: "Fellowship", competition: "Competition", training: "Training", startup: "Startup program", funding: "Funding" };
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en", { month: "long", day: "numeric", year: "numeric" }).format(new Date(value)) : "No deadline listed";
const daysLeft = (value: string | null) => value ? Math.max(0, Math.ceil((new Date(value).getTime() - Date.now()) / 86400000)) : null;
const place = (item: Opportunity) => item.is_remote ? "Remote" : item.location_label || item.country || "Open location";

function Fact({ label, value }: { label: string; value: string }) {
  return <div className="opportunity-fact"><small>{label}</small><strong>{value}</strong></div>;
}

export default function OpportunityDetailPage() {
  const { id } = useParams<{ id: string }>();
  const [item, setItem] = useState<Opportunity | null>(null); const [similar, setSimilar] = useState<Opportunity[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [tracking, setTracking] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([api<Opportunity>(`/opportunities/${id}/`), api<Page<Opportunity>>("/opportunities/")]).then(([opportunity, page]) => { setItem(opportunity); setSimilar(page.results.filter((candidate) => candidate.public_id !== opportunity.public_id && candidate.category === opportunity.category).slice(0, 3)); }).catch(() => setError("This opportunity could not be loaded.")).finally(() => setLoading(false)); }, [id]);
  if (loading) return <main className="opportunity-detail container"><p>Loading opportunity...</p></main>;
  if (!item) return <main className="opportunity-detail container"><p className="opportunity-error">{error || "Opportunity not found."}</p><Link href="/opportunities" className="text-link">Back to opportunities</Link></main>;
  const match = item.match; const remaining = daysLeft(item.deadline); const saved = Boolean(item.saved_status); const tracked = Boolean(item.application_status);
  function toggleSave() { setSaving(true); api(`/opportunities/${item.public_id}/save/`, { method: saved ? "DELETE" : "POST", body: JSON.stringify({}) }).then(() => setItem((current) => current ? { ...current, saved_status: saved ? null : "saved" } : current)).finally(() => setSaving(false)); }
  function startTracking() { setTracking(true); api<OpportunityApplication>("/opportunity-applications/", { method: "POST", body: JSON.stringify({ opportunity_id: item.public_id, status: "preparing" }) }).then((application) => setItem((current) => current ? { ...current, application_status: application.status } : current)).catch(() => {}).finally(() => setTracking(false)); }
  const facts = [{ label: "Type", value: labels[item.category] || item.category }, { label: "Location", value: place(item) }, { label: "Funding / value", value: item.benefit || "See provider details" }, { label: "Eligibility", value: item.eligible_countries?.join(", ") || item.country || "Review requirements" }, { label: "Education", value: item.education_levels?.join(", ") || "Any level" }, { label: "Provider", value: item.provider }];
  return <main className="opportunity-detail container">
    <Link href="/opportunities" className="detail-back"><ArrowLeft size={15} /> Back to opportunities</Link>
    <header className="opportunity-detail-hero"><div className="opportunity-detail-heading"><span className="opportunity-type">{labels[item.category] || item.category}</span><h1>{item.title}</h1><p>{item.provider} <span>·</span> {place(item)}</p></div><div className="opportunity-detail-actions"><a className="button button-dark" href={item.application_url} target="_blank" rel="noreferrer">Apply now <ExternalLink size={16} /></a><button className={`button button-outline${saved ? " saved" : ""}`} onClick={toggleSave} disabled={saving}><Bookmark size={16} fill={saved ? "currentColor" : "none"} />{saved ? "Saved" : "Save"}</button></div></header>
    <div className="opportunity-deadline-banner"><div><CalendarClock size={20} /><span><small>Deadline</small><strong>{formatDate(item.deadline)}</strong></span></div>{remaining !== null && <strong className="opportunity-days">{remaining} days remaining</strong>}{tracked && <span className="opportunity-tracked"><Check size={14} /> In your tracker</span>}</div>
    <div className="opportunity-detail-layout"><div className="opportunity-detail-main">
      <section className="opportunity-match-panel"><div className="opportunity-match-score"><span>{match?.score || 0}%</span><small>Your match</small></div><div><span className="eyebrow">YOUR MATCH</span><h2>You appear to meet most of the published requirements.</h2><p>Based on the information in your Getneba profile.</p></div></section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><Target size={19} /><div><h2>Why you match</h2><p>Signals from your profile that fit this opportunity.</p></div></div>{match?.reasons.length ? <div className="opportunity-check-list">{match.reasons.map((reason) => <span key={reason}><Check size={16} />{reason}</span>)}</div> : <p>Complete more of your profile to see a detailed match explanation.</p>}{match?.missing.length ? <div className="opportunity-gap"><span><Clock3 size={16} />Potential gap</span><p>{match.missing.join("; ")}</p></div> : null}</section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><Sparkles size={19} /><div><h2>Quick facts</h2><p>The details most people want to know first.</p></div></div><div className="opportunity-facts">{facts.map((fact) => <Fact key={fact.label} {...fact} />)}</div></section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><FileText size={19} /><div><h2>About this opportunity</h2></div></div><p className="opportunity-description">{item.summary}</p>{item.benefit && <><h3>What you&apos;ll get</h3><p>{item.benefit}</p></>}</section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><Check size={19} /><div><h2>Eligibility</h2><p>Review the published requirements before applying.</p></div></div><p>{item.eligibility_notes || "Review the provider's official page for full eligibility details."}</p><div className="opportunity-eligibility"><strong>Your eligibility</strong><span className={match?.score ? "eligible" : "needs-review"}>{match?.score ? "Eligible based on your profile" : "Needs more profile information"}</span></div></section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><FileText size={19} /><div><h2>What you&apos;ll need</h2><p>Confirm the exact documents on the provider&apos;s application page.</p></div></div><ul className="opportunity-requirements"><li><Check size={15} />A complete Getneba profile</li><li><Check size={15} />Your relevant supporting documents</li><li><Check size={15} />Any requirements listed by {item.provider}</li></ul></section>
      <section className="opportunity-detail-section"><div className="opportunity-detail-section-heading"><ChevronRight size={19} /><div><h2>How to apply</h2></div></div><ol className="opportunity-steps"><li><b>01</b><span>Review your eligibility and prepare your documents.</span></li><li><b>02</b><span>Open the official application website.</span></li><li><b>03</b><span>Submit your application before the deadline.</span></li></ol><a className="button button-dark" href={item.application_url} target="_blank" rel="noreferrer">Apply on official website <ExternalLink size={16} /></a></section>
    </div><aside className="opportunity-detail-aside">
      <div className="opportunity-action-card"><span className="eyebrow">KEEP MOVING</span><h2>Ready to act?</h2><p>Add this opportunity to your tracker while you prepare.</p><button className="button button-dark full-width" onClick={startTracking} disabled={tracking || tracked}>{tracked ? <><Check size={16} /> In your tracker</> : tracking ? "Adding..." : <><HeartHandshake size={16} /> I&apos;m applying</>}</button><Link className="button button-outline full-width" href="/assistant"><Sparkles size={16} /> Ask about this opportunity</Link></div>
      <div className="opportunity-deadline-card"><Bell size={18} /><div><strong>Deadline reminder</strong><p>Get a reminder before applications close.</p><button>Remind me 7 days before <ArrowUpRight size={14} /></button></div></div>
      <div className="opportunity-source-card"><span className="eyebrow">OPPORTUNITY SOURCE</span><strong>{item.provider}</strong><a href={item.source_url || item.application_url} target="_blank" rel="noreferrer">Official website <ExternalLink size={13} /></a><small>Source link provided by the organization.</small><button><Flag size={13} /> Report outdated information</button></div>
    </aside></div>
    {similar.length > 0 && <section className="opportunity-similar"><div className="opportunity-section-heading compact"><div><span className="eyebrow">KEEP EXPLORING</span><h2>You might also qualify for</h2></div></div><div className="opportunity-similar-grid">{similar.map((candidate) => <Link href={`/opportunities/${candidate.public_id}`} key={candidate.public_id}><span>{candidate.match?.score || 0}% match</span><strong>{candidate.title}</strong><small>{candidate.provider}</small><ChevronRight size={16} /></Link>)}</div></section>}
    <div className="opportunity-report-note"><X size={14} /> Getneba helps you understand opportunities; always confirm final requirements with the official provider.</div>
  </main>;
}