// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../src/app/[info]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[info]">> = Specific
  const handler = {} as typeof import("../../../src/app/[info]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../../src/app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications">> = Specific
  const handler = {} as typeof import("../../../src/app/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/assistant/interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant/interview">> = Specific
  const handler = {} as typeof import("../../../src/app/assistant/interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant">> = Specific
  const handler = {} as typeof import("../../../src/app/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credits">> = Specific
  const handler = {} as typeof import("../../../src/app/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/install/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/install">> = Specific
  const handler = {} as typeof import("../../../src/app/install/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/local-help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-help">> = Specific
  const handler = {} as typeof import("../../../src/app/local-help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/matches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matches">> = Specific
  const handler = {} as typeof import("../../../src/app/matches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/members/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/messages/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/messages/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/my-opportunities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-opportunities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/my-opportunities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/my-opportunities/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-opportunities/new">> = Specific
  const handler = {} as typeof import("../../../src/app/my-opportunities/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/my-opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/my-opportunities">> = Specific
  const handler = {} as typeof import("../../../src/app/my-opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offers/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/offers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offers/new">> = Specific
  const handler = {} as typeof import("../../../src/app/offers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offers">> = Specific
  const handler = {} as typeof import("../../../src/app/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/operations/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/[section]">> = Specific
  const handler = {} as typeof import("../../../src/app/operations/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../../src/app/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/fellowships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/fellowships">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/fellowships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/grants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/grants">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/grants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/internships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/internships">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/internships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/jobs">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/scholarships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/scholarships">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/scholarships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/startup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunities/startup">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/startup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunity-applications/[id]/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunity-applications/[id]/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunity-applications/[id]/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunity-applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunity-applications/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunity-applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunity-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opportunity-check">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunity-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/applicants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/applicants">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/applicants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/assistant">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/opportunities/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/opportunities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/opportunities/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/opportunities/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/opportunities/new">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/opportunities/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/organization/opportunities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization/opportunities">> = Specific
  const handler = {} as typeof import("../../../src/app/organization/opportunities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/safety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety">> = Specific
  const handler = {} as typeof import("../../../src/app/safety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saved">> = Specific
  const handler = {} as typeof import("../../../src/app/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../../src/app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/mine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/mine">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/mine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/new">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/u/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/u/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../../src/app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/opportunities/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/opportunities/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/opportunities/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
