"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, Bookmark, CalendarClock, Link2, Mic2, Plus, UserRound } from "lucide-react";
import { api } from "@/lib/api";
import type { OpportunityDashboard, User } from "@/lib/types";
import { OpportunityCard } from "@/components/opportunity-card";
import { opportunityPath } from "@/lib/routes";

export default function DashboardPage() {
  const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<OpportunityDashboard | null>(null); const [error, setError] = useState(""); const [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); setError(""); Promise.all([api<User>("/auth/me/", { signal: controller.signal }), api<OpportunityDashboard>("/opportunities/dashboard/", { signal: controller.signal })]).then(([profile, dashboard]) => { setUser(profile); setData(dashboard); }).catch(() => { if (!controller.signal.aborted) setError("Your home couldn’t be loaded. Please try again."); }); return () => controller.abort(); }, [retry]);
  return <main className="nb-dashboard container"><header className="nb-dashboard-heading"><div><span className="nb-kicker">YOUR NEXT CHAPTER</span><h1>{user ? `Hey ${user.display_name?.split(" ")[0] || "there"}. What’s next?` : "Your next move starts here."}</h1><p>A good find, a little preparation, a step forward.</p></div><Link href="/opportunities" className="nb-text-link">Explore opportunities <ArrowUpRight size={18} /></Link></header>
    <Link href="/my-opportunities/new" className="nb-composer"><span className="nb-composer-avatar"><Link2 size={23} /></span><span><strong>Found something worth sharing?</strong><small>A link you pass on could open a door.</small></span><span className="nb-composer-action">Share a find <Plus size={18} /></span></Link>
    {error ? <div className="nb-feedback" role="alert"><p>{error}</p><button onClick={() => setRetry((value) => value + 1)}>Try again</button></div> : !data ? <div className="nb-empty" role="status">Finding your next steps…</div> : <div className="nb-dashboard-grid"><div><div className="nb-results-heading"><h2>Worth a closer look</h2><Link href="/matches" className="nb-text-link">View all <ArrowRight size={16} /></Link></div>{data.top_matches.length ? <div className="nb-results-grid">{data.top_matches.slice(0, 4).map((item) => <OpportunityCard item={item} key={item.public_id} />)}</div> : <div className="nb-empty"><Bookmark size={27} /><h3>Let’s find something that fits.</h3><p>Add your interests to help personalise your recommendations.</p><Link href="/profile" className="nb-button nb-button-green">Add your interests <ArrowRight size={17} /></Link></div>}
      <section className="nb-progress-section"><div className="nb-results-heading"><h2>Keep moving forward</h2><Link href="/applications" className="nb-text-link">My progress <ArrowRight size={16} /></Link></div>{data.applications.length ? data.applications.slice(0, 3).map((item) => <Link href={`/applications/${item.public_id}`} className="nb-progress-row" key={item.public_id}><span className="nb-progress-icon"><ArrowUpRight size={21} /></span><div><strong>{item.opportunity.title}</strong><small>{item.next_action || item.opportunity.provider}</small></div><span className="nb-status">{item.status}</span><ArrowRight size={18} /></Link>) : <div className="nb-progress-empty"><p>Your next step deserves a place to land.</p><Link href="/opportunities">Find an opportunity to pursue <ArrowRight size={16} /></Link></div>}</section></div>
      <aside className="nb-dashboard-aside"><section className="nb-deadlines"><span className="nb-kicker"><CalendarClock size={15} /> ON YOUR RADAR</span><h2>Dates to keep close.</h2>{data.urgent.length ? data.urgent.map((item) => <Link href={opportunityPath(item.title, item.public_id)} key={item.public_id}><strong>{item.title}</strong><span>{item.deadline ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", timeZone: "Africa/Lagos" }).format(new Date(item.deadline)) : "See details"}<ArrowUpRight size={15} /></span></Link>) : <p>No upcoming deadlines to show.</p>}</section><section className="nb-aside-tip"><Mic2 size={22} /><h3>Make your next interview feel familiar.</h3><p>Practise your answers and get feedback before the real conversation.</p><Link href="/assistant/interview" className="nb-text-link">Start practising <ArrowUpRight size={16} /></Link></section><Link href="/profile" className="nb-profile-prompt"><UserRound size={21} /><span><strong>Your profile, your direction.</strong><small>Update your interests and experience.</small></span><ArrowRight size={16} /></Link></aside></div>}
  </main>;
}
