"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Bell, Bookmark, CalendarClock, Check, FileCheck2, Link2, Mic2, Search, Sparkles, Target, Upload } from "lucide-react";
import { api, getToken } from "@/lib/api";
import { Opportunity, OpportunityDashboard, User } from "@/lib/types";
import { opportunityPath } from "@/lib/routes";
import { useRouter } from "next/navigation";

const categoryMeta: Record<string, string> = { scholarship: "Learn", grant: "Fund", job: "Work", internship: "Work", fellowship: "Learn", competition: "Build", training: "Learn", startup: "Build", funding: "Fund", tender: "Build" };
function timeGreeting() { const hour = new Date().getHours(); return hour < 12 ? "morning" : hour < 18 ? "afternoon" : "evening"; }
function deadlineDays(deadline: string | null) { return deadline ? Math.ceil((new Date(deadline).getTime() - Date.now()) / 86400000) : null; }
function deadlineLabel(deadline: string | null) { const days = deadlineDays(deadline); if (days === null) return "No deadline"; if (days <= 0) return "Closes today"; return `Closes in ${days} day${days === 1 ? "" : "s"}`; }
type CreditSummary = { balance: number; earned_today: number; daily_cap: number; transactions: { amount: number; action: string; description: string; created_at: string }[] };

function MatchCard({ opp, featured = false }: { opp: Opportunity; featured?: boolean }) {
  const reasons = opp.match?.reasons || []; const location = opp.is_remote ? "Remote" : opp.location_label || opp.country || "Open location";
  return <article className={`command-match-card${featured ? " featured" : ""}`}><div className="command-match-top"><span>{categoryMeta[opp.category] || opp.category}</span><b>{opp.match?.score || 0}% <small>profile fit</small></b></div><h3>{opp.title}</h3><p className="command-match-org">{opp.provider} · {location}</p>{featured && <p className="command-match-copy">{opp.summary}</p>}<div className="command-match-meta"><span>{opp.benefit || "Opportunity"}</span><span>{deadlineLabel(opp.deadline)}</span></div>{featured && reasons.length > 0 && <div className="command-match-reasons"><small>Why you match</small>{reasons.slice(0, 3).map((reason) => <span key={reason}><Check size={13} /> {reason}</span>)}</div>}<Link href={opportunityPath(opp.title, opp.public_id)} className="command-card-link">View opportunity <ArrowRight size={14} /></Link></article>;
}

export default function DashboardPage() {
  const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [data, setData] = useState<OpportunityDashboard | null>(null); const [credits, setCredits] = useState<CreditSummary | null>(null); const [query, setQuery] = useState("");
  useEffect(() => { if (!getToken()) { router.replace("/login?next=/dashboard"); return; } Promise.all([api<User>("/auth/me/"), api<OpportunityDashboard>("/opportunities/dashboard/"), api<CreditSummary>("/auth/credits/")]).then(([profile, dashboard, creditSummary]) => { setUser(profile); setData(dashboard); setCredits(creditSummary); }).catch(() => router.replace("/login")); }, [router]);
  const firstName = user?.display_name?.split(" ")[0] || "there";
  return <main className="dash-command container"><header className="command-greeting"><div><span className="eyebrow">YOUR PERSONAL OPPORTUNITY SPACE</span><h1>Good {timeGreeting()}, {firstName}.</h1><p>Here’s what’s worth your attention today.</p></div><Link href="/alerts" className="command-alert-link"><Bell size={16} /> Alerts</Link></header><form className="command-search" onSubmit={(event) => { event.preventDefault(); if (query.trim()) router.push(`/opportunities?search=${encodeURIComponent(query)}`); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search opportunities..." aria-label="Search opportunities" />{query.trim() && <button type="submit" aria-label="Search"><ArrowRight size={17} /></button>}</form>
    {!data ? <div className="dash-loading"><Sparkles size={22} /><span>Preparing your radar…</span></div> : <>
      <div className="command-summary"><Link href="/matches"><strong>{data.match_count}</strong><span>New matches</span></Link><Link href="/saved"><strong>{data.saved.length}</strong><span>Saved</span></Link><Link href="/matches"><strong>{data.urgent.length}</strong><span>Closing soon</span></Link></div>
      {credits && <section className="command-credit-card"><div><span className="eyebrow">YOUR GETNEBA CREDITS</span><strong>{credits.balance} <small>credits</small></strong><p>Earn {Math.max(0, credits.daily_cap - credits.earned_today)} more today by contributing a useful opportunity.</p></div><Link href="/my-opportunities/new" className="section-link">Contribute an opportunity <ArrowRight size={14} /></Link></section>}
      <section className="command-section"><div className="command-section-heading"><div><span className="eyebrow"><Sparkles size={13} /> YOUR OPPORTUNITIES</span><h2>Recommended for you</h2><p>Based on your profile, interests, and activity.</p></div><Link href="/matches" className="section-link">See all recommendations <ArrowRight size={15} /></Link></div>{data.top_matches.length ? <div className="command-match-grid"><MatchCard opp={data.top_matches[0]} featured />{data.top_matches.slice(1, 4).map((opp) => <MatchCard key={opp.public_id} opp={opp} />)}</div> : <div className="command-empty"><Sparkles size={24} /><div><strong>Your radar is ready.</strong><p>Complete a little more of your profile to make recommendations sharper.</p></div><Link href="/profile" className="button button-dark compact">Improve my profile <ArrowRight size={14} /></Link></div>}</section>
      <section className="command-section command-pursuing"><div className="command-section-heading"><div><span className="eyebrow">KEEP MOVING</span><h2>You’re pursuing</h2><p>Pick up where you left off.</p></div><Link href="/applications" className="section-link">Open tracker <ArrowRight size={15} /></Link></div>{data.applications.length ? <div className="command-application-list">{data.applications.slice(0, 3).map((item) => <Link href={`/applications/${item.public_id}`} key={item.public_id}><div className="command-application-title"><strong>{item.opportunity.title}</strong><span>{item.opportunity.provider}</span></div><div className="command-application-progress"><span><i style={{ width: item.status === "applied" ? "72%" : item.status === "preparing" ? "48%" : "86%" }} /></span><b>{item.status === "applied" ? "72%" : item.status === "preparing" ? "48%" : "86%"} ready</b></div><small>Next: {item.next_action || "Review your next step"}</small><ArrowRight size={16} /></Link>)}</div> : <div className="command-empty compact"><FileCheck2 size={22} /><div><strong>No active applications yet.</strong><p>Save an opportunity or start preparing when you find one worth pursuing.</p></div><Link href="/opportunities" className="section-link">Find one <ArrowRight size={14} /></Link></div>}</section>
      <div className="command-two-column"><section className="command-section command-closing"><div className="command-section-heading"><div><span className="eyebrow">DON’T MISS THESE</span><h2>Closing soon</h2></div><Link href="/matches" className="section-link">View all <ArrowRight size={14} /></Link></div>{data.urgent.length ? <div className="command-deadline-list">{data.urgent.slice(0, 4).map((opp) => <Link href={opportunityPath(opp.title, opp.public_id)} key={opp.public_id}><div><strong>{opp.title}</strong><span>{categoryMeta[opp.category] || opp.category} · {opp.provider}</span></div><b>{deadlineLabel(opp.deadline)} <ArrowRight size={13} /></b></Link>)}</div> : <p className="command-quiet">No urgent deadlines right now.</p>}</section><section className="command-section command-readiness"><div className="command-section-heading"><div><span className="eyebrow">GET MORE READY</span><h2>Improve your readiness</h2></div><Link href="/profile" className="section-link">Profile <ArrowRight size={14} /></Link></div><div className="command-readiness-score"><strong>{data.profile_completion}%</strong><p>{data.missing_profile_fields.length ? `Adding ${data.missing_profile_fields.slice(0, 2).join(" and ").replaceAll("_", " ")} could improve your matches.` : "Your profile is giving your radar useful context."}</p></div><div className="command-readiness-bar"><span style={{ width: `${data.profile_completion}%` }} /></div><Link href={data.readiness.interview ? "/profile" : "/assistant/interview"} className="command-readiness-action">{data.readiness.interview ? "Refine my profile" : "Practice your next interview"} <ArrowRight size={14} /></Link></section></div>
      <section className="command-section command-actions"><div className="command-section-heading"><div><span className="eyebrow">CHOOSE YOUR NEXT MOVE</span><h2>What do you want to do?</h2></div></div><div className="command-action-grid"><Link href="/opportunities"><Search size={18} /><strong>Find opportunities</strong><span>Explore what’s available.</span><ArrowRight size={14} /></Link><Link href="/opportunities"><Link2 size={18} /><strong>Check an opportunity</strong><span>Bring a link from anywhere.</span><ArrowRight size={14} /></Link><Link href="/assistant"><Mic2 size={18} /><strong>Practice</strong><span>Prepare for the real moment.</span><ArrowRight size={14} /></Link><Link href="/my-opportunities/new"><Upload size={18} /><strong>Post an opportunity</strong><span>Share something worth pursuing.</span><ArrowRight size={14} /></Link></div></section>
      <section className="command-insight"><span className="command-insight-icon"><Target size={18} /></span><div><span className="eyebrow">GETNEBA NOTICED SOMETHING</span><h2>{data.missing_profile_fields.length ? "A little more context could open better matches." : "Your opportunity radar has useful context."}</h2><p>{data.missing_profile_fields.length ? `Add ${data.missing_profile_fields.slice(0, 2).join(" and ").replaceAll("_", " ")} to help Getneba understand what you can pursue next.` : "Keep exploring and saving opportunities to help your recommendations become more useful over time."}</p></div><Link href="/profile" className="section-link">See my profile <ArrowRight size={14} /></Link></section>
    </>}</main>;
}
